### ISSUE TITLE
Login page gets @Body object on Login

### ISSUE THREAD

**Issue by TurgayTurk** [neozhu/CleanArchitectureWithBlazorServer#118]
I do like the design of your custom components. I would say the best design in MudBlazor I have found so far! Thank you for your great work. Whilest playing arround with your great project I have faced a strange behaviour I want to report.
 
Login page becomes @Body object after login.

![image](https://user-images.githubusercontent.com/11562790/168889346-29856b50-2a97-4517-86a1-1ac4b3c50cac.png)

To reproduce this behaviour do following;

1) Logout (if logged in).
2) On Login page click "Sign Up" link to navigate to registration page.
3) On Sign Up (registration) page click "Sign In" link to navigate back to login page.
4) Now back on the Login page finaly click "Sign In" button (with preset admninistrator) to login.

**Comment by neozhu** [comment]
thank you， I have fixed it.
