### ISSUE TITLE
Redirect URL for Signing in using Individual Microsoft Account

### ISSUE THREAD

**Issue by 274188A** [neozhu/CleanArchitectureWithBlazorServer#122]
Hi - thanks for creating this excellent project!

I was trying to use the Individual Microsoft account login and while the login process was ok and I was authenticated the redirect back to the app after authenticating seems unusual.

Taking a look at the redirect URL ([https://mudblazor-s.dotnet6.cn/](https://mudblazor-s.dotnet6.cn/)) which appears to be China based may be the problem but not sure.
![image](https://user-images.githubusercontent.com/40014477/169720751-bf1a1abb-08db-4196-bdb3-0083098fe863.png)

What happens is the dialogue box used to login actually ends up housing the app itself (see pic below)

![image](https://user-images.githubusercontent.com/40014477/169720889-82f99656-2238-40a9-8ada-72b40bc177f8.png)

I wondering if it has something to do with the redirect URL?

Thanks once again

**Comment by 274188A** [comment]
I seemed to have resolved this by making some minor adjustment to the javascript file:
...\Blazor.Server.UI\wwwroot\js\msal\authConfig.js 

![image](https://user-images.githubusercontent.com/40014477/169723600-ed47e4b4-c922-4122-99e4-84dd2b771234.png)

So I simply created an App registration (personal accounts only) in my Azure AD.
Added a secret
Used a single page platform +set the redirect urls to the app

Hope this helps!

**Comment by neozhu** [comment]
![Screenshot 2022-05-23 203133](https://user-images.githubusercontent.com/1549611/169819884-08cbd042-ed76-4839-be90-9ce9719f3a12.jpg)
select Single-page application.

**Comment by 274188A** [comment]
Yes - my answer to myself states "single page application but the real question is why 
the need for a re-direct to an unknown [site](https://mudblazor-s.dotnet6.cn/)? it just seems confusing to me.

I believe the correct setting should the redirect not be the application that is running eg localhost....

Let me know if you would prefer me to make a pull request of clarify further

Best Regards, John

**Comment by neozhu** [comment]
The redirection url is determined by the server-side on azure, not the client configuration,

**Comment by 274188A** [comment]
Hi @neozhu  - yes I agree with you no misunderstanding there in terms of a users Azure Registered App to auth Microsoft logins.

The question I have is regarding this particular [line](https://github.com/neozhu/CleanArchitectureWithBlazorServer/blob/0098acad54775da9730186c4612042dd2e54575d/src/Blazor.Server.UI/wwwroot/js/msal/authConfig.js#L6). 

It is invoked via the server when the user clicks the Microsoft button.  The javascript then uses it's own Registered App Id and does a redirect to an unknown site that seems to look like the login screen - but the user is now looking at a different site - not their application.  This could be confusing I think.

Cheers, John

**Comment by neozhu** [comment]
redirectUri: "https://mudblazor-s.dotnet6.cn/",  Must be equal to the azure registration app redirect uri setting.
Another possibility is that it is not supported localhost domain name, maybe, I don't know.

**Comment by 274188A** [comment]
oh, i see what you're doing now.  the source code here is also used to run your demo - so that's why you have it like that - maybe a comment in the code might help other.  closing this now.

here is the way Microsoft recommends to give you external logins (zero javascript required):
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/?view=aspnetcore-6.0&tabs=visual-studio

**Comment by neozhu** [comment]
> oh, i see what you're doing now. the source code here is also used to run your demo - so that's why you have it like that - maybe a comment in the code might help other. closing this now.
> 
> here is the way Microsoft recommends to give you external logins (zero javascript required): https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/?view=aspnetcore-6.0&tabs=visual-studio

 this document only supports the asp.net core web application, not supporting blazor-server
