### ISSUE TITLE
登录慢

### ISSUE THREAD

**Issue by yfl8910** [neozhu/CleanArchitectureWithBlazorServer#146]
每次进入首页都需要登录，并且非常慢，有些资源无法load

![image](https://user-images.githubusercontent.com/2750715/181003317-d97c98e2-404c-4308-bea7-73ae5cbba622.png)

**Comment by linkxu1989** [comment]
Not seen the issue, are you using "In Memory"?

**Comment by neozhu** [comment]
Fixed, but not yet deployed
