### ISSUE TITLE
Toast (Notification) bug during user login

### ISSUE THREAD

**Issue by DiyarBakir** [neozhu/CleanArchitectureWithBlazorServer#149]
As you can look the following screenshot **User2** refresh the page and the toasts show up on all of users page that login in the app.

in the reality the toast must appear only for belonged user!

![bug](https://user-images.githubusercontent.com/877924/181066916-c40f4877-628b-46cc-a211-86c5306156e9.png)

**Comment by neozhu** [comment]
I don't think this is a big problem, but at the moment the user's online status is not updated correctly using SignalR and CircuitHandler, see if you can solve this problem

**Comment by neozhu** [comment]
fixed

**Comment by scharada** [comment]
issue still happening as of latest code.

**Comment by neozhu** [comment]
I have found a way to correctly display the user's current online status.
<img width="866" alt="image" src="https://user-images.githubusercontent.com/1549611/209455142-203a0a41-8d7f-4ad0-931a-f1ec3c04ecae.png">
