### ISSUE TITLE
Did you created a solution template for this?

### ISSUE THREAD

**Issue by dMiracleMan** [neozhu/CleanArchitectureWithBlazorServer#154]
I was wondering. 

I've been using the cleanarchitecture template for testing, but I love this one.

**Comment by neozhu** [comment]
Unfortunately, it didn't work out, maybe you can try if it does please let me know

**Comment by neozhu** [comment]
now I update it for solution templates, you can try it

**Comment by dMiracleMan** [comment]
Ok. How do I install the template?

**Comment by neozhu** [comment]
> Ok. How do I install the template?

You can read the readme file,

**Comment by dMiracleMan** [comment]
Yes, got it working. Thank you. It worked.

**Comment by sujeet07** [comment]
i follow the readme file but solution is not able to create from template, am i missing something?

**Comment by sujeet07** [comment]
> i follow the readme file but solution is not able to create from template, am i missing something?

what are the parameter need to update in templatejson file?
