### ISSUE TITLE
Disable Docker Support

### ISSUE THREAD

**Issue by jccirs09** [neozhu/CleanArchitectureWithBlazorServer#16]
Thank you for this amazing project. New in docker and blazor. I'd been trying to figure out docker for 6 hours and I couldn't grasp how you setup the entire project.
Is there any easy way to remove docker support on this project and run only on server / kestrel?

**Comment by neozhu** [comment]
Sorry, I  haven't modified the Docker-compose configuration file yet. I'll try it tonight

**Comment by neozhu** [comment]
remove docker-compose project
![image](https://user-images.githubusercontent.com/1549611/155967005-6ab5ca2a-63ab-48a4-b6e9-450c07f5c997.png)

**Comment by jccirs09** [comment]
Thank you!
There were columns not updated on the migrations. I just added new migration and it works.
