### ISSUE TITLE
Register not Validating

### ISSUE THREAD

**Issue by jccirs09** [neozhu/CleanArchitectureWithBlazorServer#19]
Hi @neozhu, the register page is not validating and not throwing any error.

![image](https://user-images.githubusercontent.com/6688028/156035912-2f45e8fa-f3ce-4339-8d5c-ad1a8939714c.png)

![image](https://user-images.githubusercontent.com/6688028/156036268-eeaf2271-dca0-41e4-bbb7-40d64f954557.png)

**Comment by neozhu** [comment]
thank for your testing.
