### ISSUE TITLE
Dependencies in the domain layer

### ISSUE THREAD

**Issue by asgharb** [neozhu/CleanArchitectureWithBlazorServer#197]
hi.
In the domain layer, you used the Entity Framework package.
Are the principles of distinct architecture respected here? Shouldn't the inner layer have no dependencies and be easily expandable?

**Comment by neozhu** [comment]
I know, Because the baseentity class needs to [NotMapped] attribute and AuditTrail entity reference PropertyEntry of EntityFrameworkCore package
