### ISSUE TITLE
Athentication Google & Microsoft

### ISSUE THREAD

**Issue by alibenchaabene** [neozhu/CleanArchitectureWithBlazorServer#198]
Authentication with Google and Microsoft Accounts not working. 

<img width="338" alt="image" src="https://user-images.githubusercontent.com/39101112/185675629-d455bbad-bb26-4ae5-90d9-8dd9f365f5f7.png">

**Comment by neozhu** [comment]
sorry, I don't know. I try it to working

**Comment by alibenchaabene** [comment]
You've add  the method   ConfirmExternal(string provider, string userName, string name, string accesstoken) in login page but never been used

**Comment by neozhu** [comment]
look at it
![image](https://user-images.githubusercontent.com/1549611/185745605-34d591c8-f5bb-4325-9445-2814e20c62c0.png)
