### ISSUE TITLE
Profile Picture in Database

### ISSUE THREAD

**Issue by BogdanJak** [neozhu/CleanArchitectureWithBlazorServer#204]
Hi Neozhu

I'm trying to change something in your project and I ran into a problem how to save the picture profile in the database.
Currently, only the link to an image on the Internet or the path to a file on the local disk is saved.
I am interested in saving the image directly to the base in binary data format.
Is it possible?

Bogdan

**Comment by neozhu** [comment]
change profile photo need re-login

**Comment by BogdanJak** [comment]
Ok, that's right.
Only that I have to save the image in the sql database in byte [] (varbinary) format

**Comment by Bram1903** [comment]
Best case scenario you should be storing images as paths in your database for quite a few reasons, which mostly can be found [here!](https://stackoverflow.com/questions/3748/storing-images-in-db-yea-or-nay) Obviously, there might be use cases where you do want to store the image as a stream in your database, but this is far from ideal and is not recommended. This issue will be closed as it doesn't have to do with the code base.
