### ISSUE TITLE
how to you recommend using this solution against an existing database?

### ISSUE THREAD

**Issue by dMiracleMan** [neozhu/CleanArchitectureWithBlazorServer#211]
For the purpose of migrating an existing application.

Thanks.

**Comment by neozhu** [comment]
refer to [migrating an existing application.](https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/migrations/existing-database)

**Comment by alibenchaabene** [comment]
Refering to data migration, the solution works fine whene i run it from VS but whene i publish it and deploy it in IIS i got an error on Program.cs on line 56 .

how can i solve it pls ?

Thanks

**Comment by neozhu** [comment]
show me error log

**Comment by alibenchaabene** [comment]
![Capture](https://user-images.githubusercontent.com/39101112/189491526-3a7ef47a-a55d-404e-a48e-74d9fe88b70d.PNG)

**Comment by neozhu** [comment]
Delete Migrations folder inside your project.
Set Database.SetInitializer<DatabaseContext>(null); inside your DatabaseContext initializer.
Delete the table __MigrationHistory inside your database. For EF6+ the table is located under Tables but for earlier versions it is located under System Tables.
Build and run.
Profit.

**Comment by Bram1903** [comment]
Since @neozhu answered this question a few months ago, and nobody replied since then, this issue is considered solved.
