### ISSUE TITLE
AddEditCommand cannot handle GUID as Id

### ISSUE THREAD

**Issue by kirkey** [neozhu/CleanArchitectureWithBlazorServer#235]
I have an existing table but with an Id of GUID type but seems cannot find an item to be updated.
But on the other hand, no problem when Id is int type.

`public async Task<Result<Guid>> Handle(AddEditContactCommand request, CancellationToken cancellationToken)
    {
        // TODO: Implement AddEditContactCommandHandler method 
        if (request.Id.Equals(Guid.Empty))
        {
            var item = _mapper.Map<Contact>(request);
            // raise a create domain event
            item.AddDomainEvent(new CreatedEvent<Contact>(item));
            _context.Contacts.Add(item);
            await _context.SaveChangesAsync(cancellationToken);
            return await Result<Guid>.SuccessAsync(item.Id);
        }
        else
        {
            var item = await _context.Contacts.FindAsync(new object[] { request.Id }, cancellationToken) ?? throw new NotFoundException($"Contact {request.Id} Not Found.");
            item = _mapper.Map(request, item);
            // raise a update domain event
            item.AddDomainEvent(new UpdatedEvent<Contact>(item));
            await _context.SaveChangesAsync(cancellationToken);
            return await Result<Guid>.SuccessAsync(item.Id);
        }
    }`

**Comment by kirkey** [comment]
Id type as Guid is possible? How about user, it has an Id as Guid. right?

**Comment by neozhu** [comment]
I think the issue is related to EntityFramework. you can refer to https://social.msdn.microsoft.com/Forums/en-US/da1a3239-d862-4518-a131-e60689e60ab7/querying-guid-fields-via-linq-statements-off-ef-models?forum=adodotnetentityframework

**Comment by kirkey** [comment]
This isn't fixed until now?

**Comment by kirkey** [comment]
Still nothing! I had to switch to another boilerplate since this issue was not fixed. It must have an auditable entity with an option of Id type which would be a selection of int or guid.

**Comment by neozhu** [comment]
Thank you for your comment. I apologize for the inconvenience caused by the issue you encountered. Unfortunately, I am unable to modify the code to support different Id key types at this time. However, I believe that using an int auto-increment type should suffice for most use cases and is also simpler to implement.
