### ISSUE TITLE
Blazor.Server.UI.Pages.User.Profile.model.get returned null

### ISSUE THREAD

**Issue by jccirs09** [neozhu/CleanArchitectureWithBlazorServer#24]
On Demo account, this is the error will show after clicking Profile.

![image](https://user-images.githubusercontent.com/6688028/156888627-0162c832-a400-4a52-9bc7-5522891a4ea4.png)

**Comment by neozhu** [comment]
I didn't find this bug, maybe using an in-memory  EF database model when restarted was not found user record by cookie.  You can try set UseInMemoryDatabase = false

**Comment by jccirs09** [comment]
I already set UseInMemoryDatabase to false. When I put it back to true I get this error.

![image](https://user-images.githubusercontent.com/6688028/156929359-589654f2-032c-43c6-9732-9b46ff7e6afb.png)

**Comment by jccirs09** [comment]
I'm currently using UseInMemoryDatabase = false that's where the bug exist. If i'm using UseInMemoryDatabase = true no problem at all.
