### ISSUE TITLE
GetAll Query Implement to MudTable

### ISSUE THREAD

**Issue by jccirs09** [neozhu/CleanArchitectureWithBlazorServer#28]
Hi @neozhu, 
Can you please show me an example of displaying data to mudtable using the GetAll query?
There are tons of example out there but I want to follow this architecture.

**Comment by neozhu** [comment]
You can refer to "GetAllKeyValuesQuery.cs" and "ProductsPaginationQuery.cs". There are two different ways to load table data.
But the above two methods are not very friendly to filter with fields. I'm waiting for update with columns filter features with mudtable component. 

if you don't use CRQS pattern. you can take a look at "https://github.com/urfnet/URF.Core" this repo.

**Comment by jccirs09** [comment]
I'm really lost, can you please show me an example displaying the data from GetAllProductsQuery.cs to MudTable?

**Comment by neozhu** [comment]
product table load data use ServerData fun;
![image](https://user-images.githubusercontent.com/1549611/157600468-7988505f-d2b2-4fd0-9160-4936d92c4f55.png)
![image](https://user-images.githubusercontent.com/1549611/157600564-09e24b11-0e09-49fc-8e24-8c9089b9b699.png)

**Comment by jccirs09** [comment]
Thank you for your quick response.
I want to use this and add some filter.  To show only where CreatedBy == Current User
![image](https://user-images.githubusercontent.com/6688028/157601975-1b7447ac-30ec-4ae9-988d-bf7e6f2d50f1.png)

![image](https://user-images.githubusercontent.com/6688028/157602092-f3714534-3499-40c8-8a04-c53f5b9467bc.png)

**Comment by jccirs09** [comment]
![image](https://user-images.githubusercontent.com/6688028/157602962-8231be68-e579-4139-ac97-cb4cf9ce8867.png)

**Comment by neozhu** [comment]
I fixed it
```
public class CurrentUserService : ICurrentUserService
{
    private readonly IHttpContextAccessor _httpContextAccessor;
    private readonly ProtectedLocalStorage _protectedLocalStorage;



    public CurrentUserService(
        IHttpContextAccessor httpContextAccessor,
        ProtectedLocalStorage protectedLocalStorage
       )
    {
        _httpContextAccessor = httpContextAccessor;
        _protectedLocalStorage = protectedLocalStorage;
    }

    public async Task<string> UserId()
    {
        try
        {
            var userId = "";
            if (_httpContextAccessor.HttpContext != null)
            {
                userId = _httpContextAccessor.HttpContext.User?.FindFirstValue(ClaimTypes.NameIdentifier);
            }
            if (string.IsNullOrEmpty(userId))
            {
                var storedPrincipal = await _protectedLocalStorage.GetAsync<string>("UserId");
                if (storedPrincipal.Success && storedPrincipal.Value is not null)
                {
                    userId = storedPrincipal.Value;
                }
            }
            return userId??String.Empty;
        }
        catch
        {
            return String.Empty;
        }
    }
}
```
Blazor server get current user state approach is different with asp.net core.
You can try to fetch new code.

**Comment by jccirs09** [comment]
Hi Thank you for all your help, I went to a different route. 
First is CreatedBy should be the Id of User? not the Name - Username
![image](https://user-images.githubusercontent.com/6688028/157818029-8bef755f-043d-4bfd-bfab-e05ea3ff97ff.png)

I achieve showing CreatedBy on products using this method (I know this might be wrong)
Adding GetUserName to claimsprincipal 
![image](https://user-images.githubusercontent.com/6688028/157818303-3e2476c7-d6c7-4f58-8889-7032640a07af.png)

Add UserId(username) on paginationfiler
![image](https://user-images.githubusercontent.com/6688028/157818452-3e0d9b90-8868-4ba8-a9dd-dbe2a2afbdad.png)

Change my query
![image](https://user-images.githubusercontent.com/6688028/157818969-99451846-3a10-45bb-928e-857776ff2dc8.png)

Then my razor page
![image](https://user-images.githubusercontent.com/6688028/157819019-176ea830-94d1-473b-b02b-3928edc64e15.png)

It does what I try to achieve but seems wrong. Specially taking out the search on my query.
