### ISSUE TITLE
System.IO.DirectoryNotFoundException: 'xx\src\Blazor.Server.UI\Files\'

### ISSUE THREAD

**Issue by linkxu1989** [neozhu/CleanArchitectureWithBlazorServer#32]
System.IO.DirectoryNotFoundException: 'xx\src\Blazor.Server.UI\Files\'
Need to commit the folder "Files/ProfilePictures".

**Comment by neozhu** [comment]
You can create the folder "Files" manual.

**Comment by linkxu1989** [comment]
Yes, I did.
