### ISSUE TITLE
When you press F5 frequently and quickly to refresh the page, the application will crash

### ISSUE THREAD

**Issue by YPcoding** [neozhu/CleanArchitectureWithBlazorServer#324]
<img width="1280" alt="BUG" src="https://user-images.githubusercontent.com/38149649/225361148-0193b7f2-5a92-435d-922f-86c06d6a85e7.png">
The information when the application crashes is shown in this picture

**Comment by neozhu** [comment]
Based on my testing, there doesn't seem to be an issue. 
https://mudblazor-s.dotnet6.cn/pages/products

**Comment by YPcoding** [comment]
After my continuous testing, the bug caused by this FluxorComponent component crashed the program, but what is the purpose of this component. I deleted it from the program, but I didn't find that it affected the program

**Comment by neozhu** [comment]
Yes, I found it too, so I removed Fluxor in this project

**Comment by neozhu** [comment]
I have fixed it, see fluxor branch

**Comment by YPcoding** [comment]
Thank you for your efforts！
