### ISSUE TITLE
Error starting the application

### ISSUE THREAD

**Issue by BogdanJak** [neozhu/CleanArchitectureWithBlazorServer#340]
I am getting the following error when running today's version of your application.

![image](https://user-images.githubusercontent.com/54505464/229714449-055c9626-18ff-4a25-9584-b90832e878be.png)

Nothing seems to have changed in this procedure. So the error is elsewhere.

Bogdan

**Comment by BogdanJak** [comment]
The error occurs when working with MS SQL Server

**Comment by neozhu** [comment]
please pull the new version

**Comment by Bram1903** [comment]
@BogdanJak, has this issue been solved?

**Comment by Bram1903** [comment]
This issue should be solved but could be reopened at any time.
