### ISSUE TITLE
Additional database engine support

### ISSUE THREAD

**Issue by Bram1903** [neozhu/CleanArchitectureWithBlazorServer#359]
Hello, 

First of all, I would like to thank you for the incredible amount of work you seem to put into this project! It already looks great, and I'm thinking of using it as a base for a new project. 

My question is if it would be possible to add additional database engine support. I saw the short mention of the MySql branch, but that branch hasn't been updated in 10 months. I normally always use PostgreSQL. I've tried to manually change the provider from MSQL to PostgreSQL's provider, but I ran into some issues, where EF JSON isn't yet supported (will be in .NET8). 

Therefore I was wondering if it is possible for you to support more database engines since Microsoft SQL server isn't exactly great for production (expensive licensing, while open src projects like PostgreSQL are around). 

Besides that MS SQL server doesn't have native support for arm processors, which is a huge issue for many. See [this issue](https://github.com/microsoft/mssql-docker/issues/734) 

Since engines like PostgreSQL are open source, and therefore free, and much better supported I'm wondering why you choose to build this project on something as expensive, and badly supported as MS SQL Server.

I really like the structure and the design of this project, and I would love to use it as a base over other options, but unfortunately not with MS SQL Server as the only database engine option. 

Thanks in advance,
Bram

**Comment by neozhu** [comment]
Hi,
Thank you for your kind words and interest in the project! I appreciate your feedback and are glad that you find it useful.
I appreciate your agreement and interest in adding PostgreSQL support to the project.  But I do not have enough time to work on it, but I welcome any contributions from the community.

If anyone is interested in contributing and submitting a pull request for PostgreSQL support, I would be more than happy to review and consider their contribution. Thank you again for your interest in the project,

**Comment by Bram1903** [comment]
This request has been implemented, with PR #367
