### ISSUE TITLE
Notification Service

### ISSUE THREAD

**Issue by Bram1903** [neozhu/CleanArchitectureWithBlazorServer#375]
The whole notification service doesn't seem to be functioning. 
I noticed the preload feature, which should send a notification when the application starts in a developer environment, but it doesn't seem to work. Besides that, I also tried to add a new notification by using the service, but that notification doesn't seem to pop up either. Could you maybe have a look?

**Comment by neozhu** [comment]
Yes， The notification menu is not yet functional because I haven't decided how to use it yet.

**Comment by Bram1903** [comment]
Ahh, that makes sense. I got confused since it seemed like an actual feature already, but I couldn't see why the notifications weren't being handled properly. I'm currently working on a PR, where I further improve certain stuff, so expect a PR soon. :-)

**Comment by neozhu** [comment]
Should I keep this Issue open and close it when it's completed? Regarding the Notification service, do you want to implement it using SignalR?

**Comment by neozhu** [comment]
@Bram1903 
I've been added to the mange group of our project. try out, you should now have the necessary permissions to close old issues and help us keep the project organized.

**Comment by Bram1903** [comment]
I just got an invite through my notifications! I indeed now have some additional permissions, so that's nice. I'll see if I can keep the issues a bit more structured by adding labels, etc. I'll also try and create a project board!
