### ISSUE TITLE
Timezone Conversions

### ISSUE THREAD

**Issue by Bram1903** [neozhu/CleanArchitectureWithBlazorServer#378]
## Problem Explained

Currently, we are storing`DateTime` based on the location of the device the application is hosted on, but we don't take into account that if someone accesses this website from another timezone it doesn't show up properly. 

We should store all the `DateTime`'s as `DateTime.UtcNow` in the database, and convert the time back to a user his local time on request. Therefore we would be able to convert a UTC timestamp back to the user his timezone, so everyone sees a timestamp in their own local format. 

I would recommend reading [this](https://www.roji.org/storing-timezones-in-the-db) very interesting article by Shay Rojansky, who is a member of the entity framework team at Microsoft, and lead developer of the PostgreSQL entity framework provider.

For example currently, because I'm using PostgreSQL I had to enable `AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);`, which results in all the timestamps being converted to UTC now when writing to the Database, but because we are only showing the end user the local saved timezone for me all the timestamps are not converted properly, which is also a problem for people who are outside of the timezone the application is hosted on.  

I suggest we start working on a proper conversion for timezones to boost this project in terms of professionalism, and production readiness. 

## Problem Example

Local console log time:

![image](https://user-images.githubusercontent.com/70259613/236202452-fafd0ab9-8bd8-4ae3-8836-6c2437108bcc.png)

Website log time:

![image](https://user-images.githubusercontent.com/70259613/236202634-7cc0bb9a-b1e0-4582-b942-1211e3d82221.png)

As you can see my current time was `14:20`, but since the `DateTime` is being saved in `UTC` the website will show up in `UTC` `12:20`. 

As I said earlier this isn't only a problem when using PostgreSQL, but also when someone would be outside of the timezone the application is hosted on, which would make it impossible to use worldwide.

**Comment by neozhu** [comment]
Thank you for your message. It's great that you are aware of the timezone issue in your project. It's true that the DateTimeService.cs file with the Now => DateTime.UtcNow code is a step in the right direction. To convert between local time and UTC time, you can use the TimeZoneInfo class in C#. This class provides methods to convert between different time zones and can be used to convert the UTC time to the local time of the user. You can also use the DateTimeOffset structure, which includes both the UTC time and the local time offset. I hope this helps! Let me know if you have any further questions.

**Comment by Bram1903** [comment]
Well, this isn't necessarily an issue with "my" project, but with the whole project in general. This is because as far as I can see we don't do any conversion, which means everybody always sees the time stored based on the device location the project is hosted on. Switching from `DateTime.Now` to `DateTime.UtcNow` in the `DateTimeService.cs` file is just a really small step since only saving the utc now times isn't necessarily a solution. We need to properly save the UTC times as an example explained in the earlier mentioned [article](https://www.roji.org/storing-timezones-in-the-db), so we can also properly convert it back. Otherwise, everyone will end up with UTC timestamps, rather than the converted timestamp based on their own location.

**Comment by neozhu** [comment]
@Bram1903 
I think it would be simpler to create two extension methods directly on the DateTime class, such as ToLocal() or ToUtc().
