### ISSUE TITLE
UI and API

### ISSUE THREAD

**Issue by lordgamefi** [neozhu/CleanArchitectureWithBlazorServer#384]
Do you intend to separate UI and Api into two separate projects?

**Comment by neozhu** [comment]
> Do you intend to separate UI and Api into two separate projects?

Hi ordgamefi,

Thank you for your comment.  I do not intend to separate the UI and API into two separate projects. I believe that the purpose of separating the front-end and back-end is to cater to different front-end technologies, such as web, mobile devices, and mini-programs. However, my project is designed to support small projects and can be used as a single browser application. Of course, with some modifications, the business logic can be written in the Application Layer, and you can simply add an ApiController to enable web API access.

**Comment by lordgamefi** [comment]
Hi @neozhu, thank you for your quick reply.
And can you add a dynamic component for the data grid? That is, an empty grid compnent, then rely on the header and datasource array to build a complete grid at runtime.

**Comment by neozhu** [comment]
@lordgamefi 
You can take a look at this website, https://mudblazor.com/  It might help you

**Comment by lordgamefi** [comment]
I agree that it is not necessary to separate the two projects. Currently, if need to integrate more mobile apps, i can not reuse the code. For example login for the app will have to write more api without taking advantage of the existing login function.

**Comment by vpetkovic** [comment]
@lordgamefi what do you mean exactly by having to write more API without taking advantage of existing login function? 

If you want to make use of the existing login function, your best option would be to leverage external login providers, also known as Single Sign-On (SSO). Even in this project setup, you can disable local login and utilize external login function with your desired Identity Provider (you can setup your own too using open-source solution such as Duende) for which you'd set up single client. However, there are a few considerations based on whether your mobile apps are XAML/MAUI apps or something else like Flutter or React Native.

If your mobile apps are XAML/MAUI based, you can create NuGet packages and share the API (not the web API) across different solutions/projects. If MAUI, you can even use the same components. If your mobile apps are part of the same solution, you can connect them to use the same infrastructure in the backend as you Blazor Server app. On the other hand, if your apps are built for example with Flutter or React Native, you can expose your services through a web API and secure them using JWT authentication configured to use the same client as your other apps. In this scenario, your mobile app would initiate the authentication flow for that client and pass the retrieved access token to the web API.
