### ISSUE TITLE
Failed to invoke hub method '"ConnectCircuit"'.

### ISSUE THREAD

**Issue by neozhu** [neozhu/CleanArchitectureWithBlazorServer#386]
Message

Failed to invoke hub method '"ConnectCircuit"'.

Exception

System.ObjectDisposedException: Cannot access a disposed object. at Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost.SetCircuitUser(ClaimsPrincipal user) at Microsoft.AspNetCore.Components.Server.ComponentHub.ConnectCircuit(String circuitIdSecret) at lambda_method39(Closure, Object) at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.ExecuteMethod(ObjectMethodExecutor methodExecutor, Hub hub, Object[] arguments) at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.<Invoke>g__ExecuteInvocation|18_0(DefaultHubDispatcher`1 dispatcher, ObjectMethodExecutor methodExecutor, THub hub, Object[] arguments, AsyncServiceScope scope, IHubActivator`1 hubActivator, HubConnectionContext connection, HubMethodInvocationMessage hubMethodInvocationMessage, Boolean isStreamCall)

![image](https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/1549611/698450c4-1f04-4a40-8513-e6445c861344)

**Comment by neozhu** [comment]
@Bram1903 
could you take a look at it?

**Comment by Bram1903** [comment]
> @Bram1903
> could you take a look at it? https://mudblazor-s.dotnet6.cn/system/logs

Shouldn't we put it on the latest version? Besides that, that website is a HUGE security risk. Since everybody has administrator permissions on that website they can all see the logs, which include client IPs. 😨

**Comment by neozhu** [comment]
@Bram1903 
You're right, I did overlook a very important privacy concern. Please make the necessary changes to the code to ensure that user privacy is protected.

**Comment by Bram1903** [comment]
> @Bram1903
> You're right, I did overlook a very important privacy concern. Please make the necessary changes to the code to ensure that user privacy is protected.

I mean, normally it's fine, because if I would have a panel, I would love to be able to log IP addresses, but for the purpose of the demo website it's far from ideal. I think we should just update that demo website to the latest version anyway, and while doing so, we just slightly modify the demo version, and remove the following two lines:

```csharp
.Enrich.WithClientIp()
.Enrich.WithClientAgent()
```

As long as the demo version doesn't include those two lines, we are good to go, but you have to manually wipe the database of the demo website, since the current version doesn't include a clear logs feature.

**Comment by Bram1903** [comment]
@neozhu, could you update the demo website to the latest version when you have time, so we can fix the security issue?

**Comment by neozhu** [comment]
I have published the demo website. I believe the error you encountered may have been caused by an additional layer of reverse proxy, which resulted in the backend IIS service experiencing websocket interruptions due to a lack of response from the client for an extended period of time.

**Comment by Bram1903** [comment]
@neozhu, what do you mean by "I have published the demo website"? It does seem to be running on the same version as a few hours ago.

When you do update it make sure to disable the two new settings I added earlier today!
