### ISSUE TITLE
Enable GitHub Security Features

### ISSUE THREAD

**Issue by Bram1903** [neozhu/CleanArchitectureWithBlazorServer#395]
I would advise enabling the free security features GitHub offers for public repositories. 

We can set it up, so it automatically reports security vulnerabilities in packages, so we are aware of packages that need to be updated more quickly, to prevent security risks. 

You can set up the settings for it under the `Security` option! Besides that, we can also add a security workflow tool like `CodeQL Analysis` on the same location by clicking on "Set up code scanning".

Showcase of what it would do with our code base:

![image](https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/70259613/f75f0c3a-9046-4ad5-bc95-79912502ba8a)

![image](https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/70259613/6ec71c9c-83b4-4c02-bad5-c23dbb558395)

**Comment by neozhu** [comment]
cool!

**Comment by Bram1903** [comment]
Yes, you seem to have configured everything correctly!
