### ISSUE TITLE
docker-compose support postgresql

### ISSUE THREAD

**Issue by neozhu** [neozhu/CleanArchitectureWithBlazorServer#397]
@Bram1903 
could you please help me improve the docker-compose deployment configuration file for this project? I need it to support both MSSQL and PostgreSQL databases, but I'm not very familiar with Docker. It would be great if you could take a look when you have some time. Thanks!

**Comment by Bram1903** [comment]
I'm quite new to Docker Composer as well, but I'll try and figure it out. Shouldn't be that hard. On the other hand I'm uncertain how you would support multiple databases within the same Docker Composer file, as it will probably just create an additional database, but maybe there is like a choose option. I'll see!

**Comment by neozhu** [comment]
you just need to add postgresql database configuration block in docker-compose.yml file. If it's not needed, you can simply comment it out.

**Comment by Bram1903** [comment]
Alright, that should be pretty straightforward! I don't have much time this weekend, but I'll be doing it Monday!

**Comment by neozhu** [comment]
> Alright, that should be pretty straightforward! I don't have much time this weekend, but I'll be doing it Monday!

Thank you for letting me know. Take your time

Thanks again for your help.

**Comment by Bram1903** [comment]
I have been trying to first get the docker composer project to work in the first place, but it's not working in the first place. Besides that, the composer project is using OS-specific directories, which will result in it only working on Windows. When changing everything to make it at least run, I get some error, which I don't understand. 

![image](https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/70259613/7167782e-8175-4517-8c81-c26befc55d61)
