### ISSUE TITLE
Awesome font

### ISSUE THREAD

**Issue by BogdanJak** [neozhu/CleanArchitectureWithBlazorServer#400]
Hi

How to add Awesome font support to your example.
The way that works on a standard application created by the VS2023 creator does not work on your example. Icons are not shown.

Bogdan

**Comment by neozhu** [comment]
Hi Bogdan,
The icon font used in the example is from the MudBlazor component library. If you're having trouble getting the icons to display, you may want to check if there are any errors related to downloading the CSS file. You can do this by opening the website and pressing F12 to open the developer tools. From there, you can check the console for any errors related to downloading the CSS file.
I hope this helps! Let me know if you have any other questions.

**Comment by Bram1903** [comment]
@BogdanJak, if you are interested in the [MudBlazor](https://mudblazor.com) icons we use, you can find the complete assortment [here](https://mudblazor.com/features/icons#icons)!

**Comment by BogdanJak** [comment]
I'm rewriting your app using Syncfusion controls. I want to completely eliminate MudBlazor from the project.
I found a solution using the Jenin.FontAwesome.Blazor library. It works very well.

**Comment by Bram1903** [comment]
> Syncfusion

May I ask why you are rewriting the application using Syncfusion? I'm interested in why you made that choice.

**Comment by BogdanJak** [comment]
I've been working with Syncfusion for several years now. First it was WPF now Blazor. It seems to me that Syncfusion has more configuration options and is more flexible. Besides, it has some components that I miss in Mudblazor (e.g. Scheduler).
And my personal feeling Grid is faster than MudBlazor.
