### ISSUE TITLE
Duende Packages

### ISSUE THREAD

**Issue by Bram1903** [neozhu/CleanArchitectureWithBlazorServer#401]
Hello,

I had a quick question. You added quite a few Duende packages to the project. Still, I don't see any actual place where you are using these packages, besides in the `CircuitHandlerService` on line 21 where you use `state.User.IsAuthenticated()`.

How necessary is it to be able to use this method, because it adds many packages to the project, which is in my opinion a bit of a overhead?

![image](https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/70259613/ae6bf0c0-5188-4ae0-a97a-46d43ec8cfde)

When deleting all of these packages it only throws an error at line 21 of the `CircuitHandlerService`.

Kind regards,
Bram

**Comment by neozhu** [comment]
Hi Bram,
If you choose not to use the Duende packages, you can use the "Microsoft.AspNetCore.Identity.*" package instead. The UserManager<DbContext> and RoleManager<DbContext> classes rely on this library.

By using "Microsoft.AspNetCore.Identity.*," you will be able to achieve similar functionality without the need for the additional Duende packages. 

you can try out it

**Comment by Bram1903** [comment]
Well, that's the thing. They don't seem to be used. When I remove all the `Duende` packages and remove the `state.User.IsAuthenticated()` the whole application still works completely fine.

**Comment by neozhu** [comment]
I think we should remove the Duende package because it is not entirely free. I will take the time to replace it with Microsoft.AspNetCore.Identity.* at some point.
