### ISSUE TITLE
MudBlazor 6.4.0 PopoverService Bug for Blazor Server-Side

### ISSUE THREAD

**Issue by Bram1903** [neozhu/CleanArchitectureWithBlazorServer#404]
Hello again :-),

I'm working on this project, and when I upgraded to `MudBlazor 1.4.0` my entire application starts to throw errors when a client tries to connect, so I tried to update MudBlazor for this project in a local branch, and your application seems to crash as well.

Other people already encountered the same problems as well as shown in [this issue](https://github.com/MudBlazor/MudBlazor/issues/6980). A [fix is already being implemented](https://github.com/MudBlazor/MudBlazor/pull/6981), but some discussion is still going on, on how to solve this issue in the best way possible.

I thought I'll let you know! 

Kind regards,
Bram

**Comment by Bram1903** [comment]
> me too,
> <img alt="image" width="463" src="https://user-images.githubusercontent.com/1549611/244388676-0b7ccbf3-5966-4887-9950-8b42d60c348e.png">
> Likewise, I believe this is a bug. People have also reported this issue under the MudBlazor project. We'll have to wait for a new patch to be released.

Yeah, indeed, but I thought I'll let you know, so you won't get confused when you were updating your packages!
We just have to play the waiting game ;-)

**Comment by Bram1903** [comment]
### Awaiting Upstream Bug Fix

**Comment by henon** [comment]
> ### Awaiting Upstream Bug Fix

Here you are: https://github.com/MudBlazor/MudBlazor/releases/tag/v6.4.1

Huge thanks @ScarletKuro for fixing this promtly. @Bram1903 please let us know if the issue is fully resolved.

**Comment by henon** [comment]
See #6980

**Comment by Bram1903** [comment]
@henon 

Thank ScarletKuro and you for implementing this fix this quickly! I've updated MudBlazor to version `6.4.1`, and everything works fine again!

Again, thanks for the incredibly fast patch!

Kind regards,
Bram
