### ISSUE TITLE
Superior dropdown empty 

### ISSUE THREAD

**Issue by 274188A** [neozhu/CleanArchitectureWithBlazorServer#406]
When creating a new user the Superior dropdown is not populated and the field is required.

I'm using latest code from main branch with SQLite

Is this a bug or maybe I'm missing a step?

![image](https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/40014477/e084fa6d-6a3f-401d-ac7a-4fea24709ee5)

Thanks!

**Comment by Bram1903** [comment]
Hello @274188A,

Are you in development mode, if so, a few users are being generated automatically. The reason why they might not show up in the "Select Superior" dropdown is that those fields are being filled depending on what `Tentan` you have selected. Try setting `Slave` to `Master`, and check if you are now able to select a superior. 

However @neozhu, if no user is present in a tenant, I can't figure out how to create a new account without a superior either. Could you take a look?

**Comment by 274188A** [comment]
Thanks , yeah I have a brand new Tenant so this blocked me a bit.  I can see where we would need to fix it but my thoughts may not fit in with the owner.

my 2 c
So for a new tenant, if there are no other users in that tenant then the field need not be shown.
From that point on, we need to populate users from the tenant (excluding themselves).

**Comment by Bram1903** [comment]
That sounds like a good solution to me!

@neozhu What are your thoughts on this, or are we both overseeing something?

**Comment by neozhu** [comment]
hi,
Regarding "Select Superior," I think the TenantId filter condition should be removed or allowed to be empty. The requirement of this mandatory field is hardcoded in the backend code, stating that it must be filled by non-admin users.

**Comment by 274188A** [comment]
I see - so if I understood correctly, there is a relationship between a 'Superior' and the 'TenantId' of a user?
