### ISSUE TITLE
Introductions for the projects developed using Blazor Server Clean Architecture

### ISSUE THREAD

**Issue by neozhu** [neozhu/CleanArchitectureWithBlazorServer#410]
1. Facial Recognition Application:
   This application utilizes the camera to recognize faces and extract relevant information. It can be used for identity verification purposes. GitHub Repository: [FacialRecognition](https://github.com/neozhu/FacialRecognition)
   Demo Video: [Link to Demo Video](https://youtu.be/SU3F0clEbRE)
[![Watch the video](https://raw.githubusercontent.com/neozhu/FacialRecognition/main/doc/Facial-Recognition-Security-Issues.jpeg)](https://youtu.be/SU3F0clEbRE)

2. Image Classification Application:
   This application employs AI to identify and classify people and objects in images. It allows for easy querying and sorting of images based on the identified content. GitHub Repository: [IntelliAlbum](https://github.com/neozhu/IntelliAlbum)
   Demo Video: [Link to Demo Video](https://youtu.be/_ZWo40zjfbQ)
[![Watch the video](https://raw.githubusercontent.com/neozhu/IntelliAlbum/main/doc/architecture.png)](https://youtu.be/_ZWo40zjfbQ)

3. Visitor Management System:
   This system facilitates a simple visitor flow process, starting from the visitor's application to approval, confirmation (via QR code scanning), and departure. GitHub Repository: [VisitorManagement](https://github.com/neozhu/visitormanagement){:target="_blank"}
   Demo Video: [Link to Demo Video](https://youtu.be/vO4fD7GG5Vc)
[![Watch the video](https://raw.githubusercontent.com/neozhu/visitormanagement/main/doc/flow_chart.jpg)](https://youtu.be/vO4fD7GG5Vc)

4. Enterprise Internal Approval Workflow Application:
   This application is a comprehensive workflow system designed for handling various form-based approval processes within an enterprise. It includes features such as complex approval workflows, email notifications, and more. All the aforementioned applications were developed using the Blazor framework.
   Demo Video: [Link to Demo Video][(https://youtu.be/vO4fD7GG5Vc](https://youtu.be/Tr9utCQvovA))
[![Watch the video](https://github-production-user-asset-6210df.s3.amazonaws.com/1549611/246611646-ad286498-8459-42c1-88dd-92776bfd35ae.png)](https://youtu.be/Tr9utCQvovA)

**Comment by Bram1903** [comment]
@neozhu,

This seems like a great project which you developed using Blazor Server Clean Architecture, however, documentation here is probably not the best place.

Have you ever looked into using the built-in Wiki features that GitHub offers for each repository? You can find it in the list of options like code, issues, pull requests, etc, or you can click [here](https://github.com/neozhu/CleanArchitectureWithBlazorServer/wiki)!

We can also use that Wiki to explain certain coding difficulties you came across when coding this project base, or document other parts of the project!

**Comment by neozhu** [comment]
@Bram1903 
Thank you for your message. I haven't explored many advanced features of GitHub yet, so I still have a lot to learn, including from you. In fact, the reason I shared this content was to attract some paid development projects or tasks, but I've realized it's not as easy as I thought. :)

**Comment by Bram1903** [comment]
Haha, all good man. About attracting paid development projects, yes, that's an incredibly hard task, since we live in a big world with many open-source projects, however as long as you stay consistent with the updates one-day such project might show up ;-)

Besides that, we don't know if people used this project for their paid platform without us knowing, since that's the power of open source. If they decided on using this code base, they probably just downloaded our code base and made their own adjustments to it in a private environment, and we would never know.

**Comment by neozhu** [comment]
Haha, thanks for understanding. You're absolutely right, attracting paid development projects can be quite challenging.

we can only seek spiritual fulfillment, and even if it's just for one like, it's still worth it.
