### ISSUE TITLE
Problem with authentication

### ISSUE THREAD

**Issue by BogdanJak** [neozhu/CleanArchitectureWithBlazorServer#414]
Hello

Gentlemen, please help me

Attached is a code sample with your modified application. I don't know where I'm making a mistake but after starting the application, the login page or home page does not open.
You can see where the error is. I don't feel very confident in authentication processes. I can't draw any more.
[OrganizerPRO.zip](https://github.com/neozhu/CleanArchitectureWithBlazorServer/files/11834021/OrganizerPRO.zip)

**Comment by neozhu** [comment]
@BogdanJak 
I would strongly advise against modifying the namespaces of this project, including the "ApplicationDbContext". There are too many parts that require refactoring, which means you will need to invest significant time in debugging and fixing issues. Moreover, I haven't done testing in this regard. Please reconsider your approach.

**Comment by Bram1903** [comment]
@BogdanJak, 

As follow up to Neozhu his response, refactoring the namespaces and other important classes within this project is quite difficult. I have done so myself, but it takes a lot of refactoring and debugging in order to get everything to work properly again. Even when you think everything is working again, some things may still not function properly. 

Besides that, I'm not going to download a random `.zip` file to check your code. You are better of pushing that code to your own respority, and then sent us a link to that respority, from a security point of view. 

Kind regards,
Bram

**Comment by BogdanJak** [comment]
I don't mind the naming.
However, I have an aversion to MudBlazor. The sole purpose of my attempt to rework your design is to eliminate MudBlazor entirely and replace it with Syncfusion controls. Unfortunately, I am doing something wrong because on a different version (after removing all references to MudBlazor) I also stop at the same stage, i.e. the login page does not start.

**Comment by Bram1903** [comment]
> I don't mind the naming.
> However, I have an aversion to MudBlazor. The sole purpose of my attempt to rework your design is to eliminate MudBlazor entirely and replace it with Syncfusion controls. Unfortunately, I am doing something wrong because on a different version (after removing all references to MudBlazor) I also stop at the same stage, i.e. the login page does not start.

Well, I mean, we built our login screen in MudBlazor, so you'll have to rewrite that page if you removed MudBlazor?

**Comment by BogdanJak** [comment]
I have a login page rewritten :-).
Everything worked until I removed references to MudBlazor from ConfigureServices.cs to be exact

//services.AddMudBlazorDialog();
//services.AddMudServices(config =>
//{
// config.SnackbarConfiguration.PositionClass = Defaults.Classes.Position.BottomRight;
// config.SnackbarConfiguration.PreventDuplicates = false;
// config.SnackbarConfiguration.NewestOnTop = true;
// config.SnackbarConfiguration.ShowCloseIcon = true;
// config.SnackbarConfiguration.VisibleStateDuration = 4000;
// config.SnackbarConfiguration.HideTransitionDuration = 500;
// config.SnackbarConfiguration.ShowTransitionDuration = 500;
// config.SnackbarConfiguration.SnackbarVariant = Variant.Filled;
//});
//services.AddMudExtensions();

**Comment by Bram1903** [comment]
So just to be clear, you have rewritten the login page, which was working fine with the new rewrite, until you removed those mud services from the services pipeline?

**Comment by BogdanJak** [comment]
exactly. After restoring these lines - the login page starts correctly.

**Comment by Bram1903** [comment]
@neozhu Would you have any idea why the login page might not function after removing the `MudBlazorDialog` or `MudExtension`?

**Comment by BogdanJak** [comment]
I played a bit with different settings and exactly disabling this fragment causes the lack of entering the login page

//services.AddMudServices(config =>
//{
//    config.SnackbarConfiguration.PositionClass = Defaults.Classes.Position.BottomRight;
//    config.SnackbarConfiguration.PreventDuplicates = false;
//    config.SnackbarConfiguration.NewestOnTop = true;
//    config.SnackbarConfiguration.ShowCloseIcon = true;
//    config.SnackbarConfiguration.VisibleStateDuration = 4000;
//    config.SnackbarConfiguration.HideTransitionDuration = 500;
//    config.SnackbarConfiguration.ShowTransitionDuration = 500;
//    config.SnackbarConfiguration.SnackbarVariant = Variant.Filled;
//});

**Comment by neozhu** [comment]
> @neozhu Would you have any idea why the login page might not function after removing the `MudBlazorDialog` or `MudExtension`?

Yes, I did use the Password TextInput control, which is part of MudExtension. Therefore, you need to replace all the TextInput controls, which is indeed a significant task.

**Comment by BogdanJak** [comment]
I don't have such a control on the Login.razor page. All listed with Syncfusion controls.

Below is the code of the Login.razor page

`
@page "/pages/authentication/login"
@inject AccessTokenProvider TokenProvider
@inject IJSRuntime JS
@inject ILocalizationService LOC

@inherits OwningComponentBase
@using Infrastructure.Services.JWT
@using Microsoft.AspNetCore.DataProtection
@using Application.Common.Security
@using Application.Constants.Role
@using Application.Constants.User
@using OrganizerPRO.Pages.Identity.Users
@using Application.Common.ExceptionHandlers


@implements IDisposable


<PageTitle>Login</PageTitle>
<AuthorizeView>
    <NotAuthorized Context="auth">
        <div id="logincard" class="card" style="width:500px; height:600px; background-color:@BackgroundColor;">
            <h4 class="card-header">@LOC["Global_Login"]</h4>
            <div class="card-body">
                <EditForm EditContext="@_contextEditLogin" OnValidSubmit="HandleValidSubmit">
                    <FluentValidationValidator/>

                    <div class="row g-0" style="text-align:center;">
                        <label style="font-size:14px;">@LOC["Global_NotAccount"]</label>
                        <a class="nav-link" style="font-size:14px; color:greenyellow; text-decoration-line:underline;" href="/pages/authentication/register">@LOC["Global_Sign_up"]</a>
                    </div>

                    <div class="row" style="margin-top:10px; margin-bottom:10px;">
                        <SfTextBox Placeholder=@LOC["Global_User_Name"] FloatLabelType="FloatLabelType.Auto" style="height:40px; font-size:18px;"
                        @bind-Value="model.UserName">
                        </SfTextBox>
                        <ValidationMessage For="@(()=>model.UserName)"></ValidationMessage>
                    </div>


                    <div class="row" style="margin-top:10px; margin-bottom:10px;">
                        <SfTextBox Placeholder=@LOC["Global_Password"] FloatLabelType="FloatLabelType.Auto" style="height:40px; font-size:18px;"
                        @bind-Value="model.Password" Type="@passtype"
                                   Created="AddIcon" @ref="_passTxt">
                        </SfTextBox>
                        <ValidationMessage For="@(()=>model.Password)"></ValidationMessage>
                    </div>

                    <div Class="d-flex justify-space-between align-center" style="margin-top:10px; margin-bottom:10px;">
                        <SfCheckBox @bind-Checked="model.RememberMe" Label=@LOC["Global_Remember_me"] style="font-size:16px;"></SfCheckBox>
                        <SfButton CssClass="e-link" style="font-size:14px;" @onclick="ForgotPass">@LOC["Global_Forgot_Pass"]</SfButton>
                    </div>

                    <div class="row" style="margin-top:10px; margin-bottom:10px;">
                        <SfProgressButton Content=@LOC["Global_Sign_in"] @onclick="OnSubmit" EnableProgress="true" IsPrimary="true" style="width:100%; padding:10px, 300px, 10px, 10px;">
                            <ProgressButtonSpinSettings Position="SpinPosition.Center"/>
                            <ProgressButtonAnimationSettings Effect= "Syncfusion.Blazor.SplitButtons.AnimationEffect.SlideLeft"/> 
                        </SfProgressButton>
                    </div>
                    
                    <div class="d-flex justify-space-around flex-grow-1 my-4 gap-4">
                        <SfButton Class="flex-grow-1" OnClick="@(()=>SignInExternal("Microsoft"))" IconCss="fab fa-Microsoft"
                                  title="Sign in with Microsoft">
                            @ConstantString.Microsoft
                        </SfButton>
                        <SfButton Class="flex-grow-1" OnClick="@(()=>SignInExternal("Google"))" IconCss="fab fa-google"
                                  title="Sign in with Google">
                            @ConstantString.Google
                        </SfButton>
                    </div>

                    <div Class="d-flex justify-space-between align-center" style="margin-top:10px; margin-bottom:10px;">
                        <img src="/images/Flagi/pl.png" style="height:24px; width:36px;" @onclick="LanguagePL"/>
                        <img src="/images/Flagi/gb.png" style="height:24px; width:36px;" @onclick="LanguageGB" />
                        <img src="/images/Flagi/de.png" style="height:24px; width:36px;" @onclick="LanguageDE"/>
                        <img src="/images/Flagi/fr.png" style="height:24px; width:36px;" @onclick="LanguageFR"/>
                        <img src="/images/Flagi/ru.png" style="height:24px; width:36px;" @onclick="LanguageRU"/>
                        <img src="/images/Flagi/es.png" style="height:24px; width:36px;" @onclick="LanguageES"/>
                    </div>
                </EditForm>
            </div>
        </div>
    </NotAuthorized>
    <Authorized>
        <RedirectToHome></RedirectToHome>
    </Authorized>
</AuthorizeView>

@code {

    public Syncfusion.Blazor.Inputs.InputType passtype = Syncfusion.Blazor.Inputs.InputType.Password;
    SfTextBox? _passTxt;
    public string Title = "Sign In";  
}
`

**Comment by BogdanJak** [comment]
Here is the link to my repository

https://github.com/BogdanJak/OrganizerPRO

If I remove the fragment >autostart="false"< from the following script - the login page is opened. However, the token is probably not saved - because I have to log in every time I start the application.

<script src="_framework/blazor.server.js" autostart="false"></script>

**Comment by BogdanJak** [comment]
Silence

**Comment by Bram1903** [comment]
> Silence

I mean, we are all extremely busy with our actual job, and besides that are trying to properly maintain this reposrity. We don't just have the time to take a look at someone else their custom codebase which doesn't work, and neither should you expect that from us. Maybe once someone has the time they will take a look, but since we are extremely busy it doesn't have a high priority.

**Comment by BogdanJak** [comment]
There is no sign of MudBlazor - everything works fine. I replaced everything via Syncfusion controls. Syncfusion color themes - great thing.

**Comment by neozhu** [comment]
@BogdanJak Syncfusion isn't free, right?

**Comment by Bram1903** [comment]
Inactive
