### ISSUE TITLE
Updated: Issue Labels

### ISSUE THREAD

**Issue by Bram1903** [neozhu/CleanArchitectureWithBlazorServer#427]
### Applied Changes
I modified some of our issue labels, to better suit our use case.
If you wish to see/modify them yourself, you can find them [here](https://github.com/neozhu/CleanArchitectureWithBlazorServer/issues/labels)!

You can close this issue if you are fine with it. Obviously, we can constantly update these labels as we wish!
If you think I missed an important one, feel free to add/update it!

### Showcase

![image](https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/70259613/01f27960-946e-45e4-9ed2-c8c0c42c2244)

**Comment by neozhu** [comment]
Thank you.
