### ISSUE TITLE
Install template issue

### ISSUE THREAD

**Issue by jochem4207** [neozhu/CleanArchitectureWithBlazorServer#428]
Hey Neozhu,

I'm very happy this template exists and i'm going to try to make it work. I can download the code and that will probably work. But in the readme there is a section says `dotnet new ca-blazor-sln`. I don't have this command after running `dotnet new --install sayedha.templates`

I tried to create that template.json but that didn't add anything to having the 'ca-blazor-sln' command.

Can you help/provide explanation what I should do?

**Comment by neozhu** [comment]
To be honest, I don't yet have knowledge of how to create custom project templates, but I'll give it a try as it doesn't seem difficult. When I have time, I will improve this feature.

**Comment by jochem4207** [comment]
Thank you! That makes sense, we can't all know it. But it was in the readme so I assumed it was there.

Mainly i'm struggling / missing a simple how to get this project up and running for myself. Which docker commands in a simple step-by-step guide. Thats why I was trying the `dotnet new ca-blazor-sln` command.

Anyway thank you for building this template!

**Comment by Bram1903** [comment]
> Thank you! That makes sense, we can't all know it. But it was in the readme so I assumed it was there.
> 
> Mainly i'm struggling / missing a simple how to get this project up and running for myself. Which docker commands in a simple step-by-step guide. Thats why I was trying the `dotnet new ca-blazor-sln` command.
> 
> Anyway thank you for building this template!
> 
> Edit: Somehow it started working after 2-3 tries, without docker, without magic. My question is solved. Ofcourse the template would be nice. But thats #429

Having a template would indeed be really nice, however for now, you could go ahead and rename all the namespaces and the application name. I successfully was able to do it, so I believe in you ;-)

**Comment by neozhu** [comment]
What? Has the problem been resolved? Can projects be created using the template now?

**Comment by jochem4207** [comment]
No, I can't create the template with a simple command (as in `dotnet new ca-blazor-sln` but the #429  was created so I figured the progress would be in there.

@Bram1903 I dont understand where your comment is coming from and why

**Comment by Bram1903** [comment]
> What? Has the problem been resolved? Can projects be created using the template now?

No, I meant that it is possible to manually rename the project including all of its corresponding namespaces. I successfully was able to do so at least. Obviously, a template would be better, since you don't have to go through the pain of changing everything manually, since it's an extremely annoying job. However, it is definitely possible to do it manually.

**Comment by neozhu** [comment]
I think you can now use templates to create your own projects, including new namespaces. I'll update the content of the readme, and some tests and adjustments may still need to be made.

**Comment by jochem4207** [comment]
@neozhu thank you the update made it more clear! I am coming from this repo (https://[github.com/jasontaylordev/CleanArchitecture](https://github.com/jasontaylordev/CleanArchitecture) and this guy put it in like the official library. So I was confused that I first had to download the repo, then create my own local .net template to install it somewhere else locally.

I would add the steps like

1. Download/Clone this repo
2. Unzip
3. Run `dotnet new install ./` //this puts the repo into a local .net template
<Continue with documentation>

(This all is in your implicit if I take a good look at your screenshot) but its not obvious to me as a new dotnet template user coming from a repo that has 1 line I need to execute.

**Comment by neozhu** [comment]
> @neozhu thank you the update made it more clear! I am coming from this repo (https://[github.com/jasontaylordev/CleanArchitecture](https://github.com/jasontaylordev/CleanArchitecture) and this guy put it in like the official library. So I was confused that I first had to download the repo, then create my own local .net template to install it somewhere else locally.
> 
> I would add the steps like
> 
> 1. Download/Clone this repo
> 2. Unzip
> 3. Run `dotnet new install ./` //this puts the repo into a local .net template
> 
> (This all is in your implicit if I take a good look at your screenshot) but its not obvious to me as a new dotnet template user coming from a repo that has 1 line I need to execute.

I create a nuget library https://www.nuget.org/packages/CleanArchitecture.Blazor.Solution.Template/1.0.0-preview.1
and I add build package action to deploy to nuget when pushing the branch main.

I am not sure it's working.

**Comment by jochem4207** [comment]
Seems to work perfectly for me

I ran `dotnet new install CleanArchitecture.Blazor.Solution.Template::1.0.0-preview.1` and ` dotnet new ca-blazorserver-sln -n <MyProjectName>`.

Seems to create the correct structure and everything.

**Comment by neozhu** [comment]
I found a minor issue; the Solution directory structure created by creating a new project menu in visual studio 2022 is different from the project structure in the source code. Please refer to the picture I have uploaded.
<img width="767" alt="image" src="https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/1549611/a101d3f7-3ebd-4f5f-884f-79f8072ddf3f">

<img width="376" alt="image" src="https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/1549611/399d415d-997f-42e9-a90a-5f11e3022039">
