### ISSUE TITLE
Error on new account profile

### ISSUE THREAD

**Issue by jccirs09** [neozhu/CleanArchitectureWithBlazorServer#43]
![image](https://user-images.githubusercontent.com/6688028/158528763-bc6b674f-cc82-41d0-93d9-4069c8babd04.png)
![image](https://user-images.githubusercontent.com/6688028/158529243-7d471d02-fac7-4337-8528-a6a46dd3c45c.png)

**Comment by neozhu** [comment]
try again

**Comment by jccirs09** [comment]
It works, and now not updating the profile picture.
