### ISSUE TITLE
How does this compare to the blazer hero project? 

### ISSUE THREAD

**Issue by punkouter23** [neozhu/CleanArchitectureWithBlazorServer#437]
one is server mode one is client mode. 

But besides that any major differences ?

**Comment by Bram1903** [comment]
Hello, 

Both BlazorHero and we are applying [the principles of clean architecture](https://learn.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/common-web-application-architectures), and we are both using the [MudBlazor component library](https://mudblazor.com).

Nevertheless, BlazorHero is still on `.NET6`, while we are on `.NET7`, which feature plans to migrate to `.NET8`. Besides that, BlazorHero hasn't been updated in over 2 years, while we are actively working on this project.

I hope this has answered your question.

Kind regards,
Bram

**Comment by jochem4207** [comment]
@Bram1903 so happy to hear you guys wanna migrate it to .NET8. You two should really add a "buy me coffee"' or something donate link add

**Comment by neozhu** [comment]
@jochem4207, thank you for your support and suggestions! I don't think it's necessary because it won't change anything. By the way, I want to mention that the biggest advantage of this project is that I have developed a code generation extension for vs.net for this project, which can greatly reduce repetitive work."

**Comment by Bram1903** [comment]
> @jochem4207, thank you for your support and suggestions! I don't think it's necessary because it won't change anything. By the way, I want to mention that the biggest advantage of this project is that I have developed a code generation extension for vs.net for this project, which can greatly reduce repetitive work."

What do you mean by `I don't think it's necessary`? Upgrading to `.NET8`?

**Comment by neozhu** [comment]
> donate

**Comment by Bram1903** [comment]
Oh, hahaha. I thought you meant not upgrading to `.NET8` at one point. You got me worried a bit haha

**Comment by 274188A** [comment]
Thanks for this fantastic project!

Where can we locate the code gen tool?

**Comment by neozhu** [comment]
@jochem4207 
Thank you for the positive feedback! I'm glad you appreciate the open-source nature of the tool. I've noted your suggestion about the donation button, and I'll definitely consider implementing it. By the way, I'm currently working on another project （ https://schoolbus.blazorserver.com/ ）related to an application that tracks students' card swipes when they get on and off school buses. I'm planning to open donations for this project in the future. Your support and feedback mean a lot. Keep enjoying and let me know if there's anything else! <3
