### ISSUE TITLE
CodeGenerator

### ISSUE THREAD

**Issue by jochem4207** [neozhu/CleanArchitectureWithBlazorServer#445]
Hey @neozhu and @Bram1903 

Still extremly happy with the project. I'm trying to use the codegenerator (yes i know it's on different github repo). I've installed vs 2022 community edition and when I generate stuff for any class i've is that it isn't compilable after. 

In the DTO's `mapFrom` is used and that isn't the case in this source code. 

Code it generates:
```
public class SoftwareDto:IMapFrom<Software>
{
    public void Mapping(Profile profile)
    {
        profile.CreateMap<Software, SoftwareDto>().ReverseMap();
    }
    // TODO: define data transfer object (DTO) fields, for example:
        [Description("Id")]
    public int Id {get;set;} 
    [Description("Name")]
    public string Name {get;set;} = String.Empty; 
    [Description("Description")]
    public string? Description {get;set;} 

}

```
ProductDTO in this repo is like:

```
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

namespace myapp.Application.Features.Products.DTOs;

[Description("Products")]
public class ProductDto
{
    [Description("Id")] public int Id { get; set; }

    [Description("Product Name")] public string? Name { get; set; }

    [Description("Description")] public string? Description { get; set; }

    [Description("Unit")] public string? Unit { get; set; }

    [Description("Brand Name")] public string? Brand { get; set; }

    [Description("Price")] public decimal Price { get; set; }

    [Description("Pictures")] public List<ProductImage>? Pictures { get; set; }

    private class Mapping : Profile
    {
        public Mapping()
        {
            CreateMap<Product, ProductDto>().ReverseMap();
        }
    }
}
```
MapFrom is used in multiple files it generates so its a little bit of cleaning up to make use of it.

It's still quite a headstart to use the generator. But could you take a look and see what's wrong compared to project here?

**Comment by jochem4207** [comment]
Thank you @Bram1903 for labelling it.

I also notice in the `Export<Item>Query.cs` that the structure of getting localizer names has changed

<img width="1230" alt="image" src="https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/4976335/c1278b8b-ae08-4455-b3aa-dc741a26e59b">

**Comment by neozhu** [comment]
Your project's source code isn't up-to-date, and neither is your code generation extension. Therefore, the code that's being generated is unusable and compiled.

**Comment by jochem4207** [comment]
@neozhu will try to update it, I just downloaded the extension from the store.

**Comment by jochem4207** [comment]
@neozhu how should I update it? should I build it myself based on the repo? this is the installed version.

<img width="242" alt="image" src="https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/4976335/e4981995-bb01-4590-9a1a-0f03c9915212">


I created my solution max two weeks ago when we talked about the command line install.

**Comment by jochem4207** [comment]
Hey @neozhu thank you for the quick reply. I see the repo is updated on 9 april and the vsix extension on here https://marketplace.visualstudio.com/items?itemName=SmartCodeMVC5Enginever3898.247365 is updated on 23 march. Maybe the last version isn't in the marketplace? Or am I missing something.

**Comment by neozhu** [comment]
> @neozhu will try to update it, I just downloaded the extension from the store.

no, you need clone this repo:https://github.com/neozhu/CleanArchitectureCodeGenerator , and build it then install it in bin

**Comment by jochem4207** [comment]
> > @neozhu will try to update it, I just downloaded the extension from the store.
> 
> no, you need clone this repo:https://github.com/neozhu/CleanArchitectureCodeGenerator , and build it then install it in bin

I've done that and it still keeps generating the old one, even after removing the old version. Rebooting the full pc. But it feels like this part is an issue on my end.

I would advise to put this in the readme

**Comment by neozhu** [comment]
I will set a action for Publish extension to Marketplace

**Comment by jochem4207** [comment]
> I will set a action for Publish extension to Marketplace

Thank you but its also really cool to have access to the extension code, if I e.g. want to update generated UI template I can do that. It's really cool, ty for learning me all this by having this repo public and answering questions

**Comment by neozhu** [comment]
> > I will set a action for Publish extension to Marketplace
> 
> Thank you but its also really cool to have access to the extension code, if I e.g. want to update generated UI template I can do that. It's really cool, ty for learning me all this by having this repo public and answering questions

https://www.vsixgallery.com/extension/6A168388-B6A2-42F9-BA5A-B577D3CD4DB5

**Comment by jochem4207** [comment]
@neozhu you're amazing !
