### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by jochem4207** [neozhu/CleanArchitectureWithBlazorServer#451]
Hey Guys,

I'm absolutely loving this project. Just started working with HangFire and seems to work well! 
I noticed while going trough some files that your google analytics ID is in here. Maybe that should be changed to an empty value or something.

It's in `ConfigureServices.cs` in Blazor.Server.UI project

**Comment by Bram1903** [comment]
Hey,

I'm not sure whether @neozhu tries to observe how many people are using the codebase, or that it should be configurable. 
@neozhu, what's the idea behind having the Google analytics id hardcoded? If you want I can make it configurable?

Kind regards,
Bram

**Comment by neozhu** [comment]
To be honest, I am not sure about the specific uses of Google Analytics. I simply copied the configuration from Microsoft's official settings. If it is not necessary, I think we can remove it. 
@Bram1903 Bram, I would greatly appreciate it if you could help make it configurable so that users can decide whether to enable Google Analytics themselves."

**Comment by Bram1903** [comment]
@neozhu, see #452.

**Comment by jochem4207** [comment]
Holy shit that was quick :)

**Comment by Bram1903** [comment]
> Holy shit that was quick :)

Haha, indeed, it was quite swift! After waking up and seeing Neozhu's request to make it configurable, I promptly worked on the entire update, finishing it in approximately 15 minutes. Thank you for bringing up this issue. Is there anything else you would like to discuss or need help with?

**Comment by neozhu** [comment]
@Bram1903  Thanks  for your effort and support

**Comment by jochem4207** [comment]
@Bram1903 damn, super speed.

At the moment just working on building the CRUD interface and on recurring HangFire Jobs. I'm curious if and how they can be created following the Clean Architecture. I want them to run monthly/daily etc.

Now I created a UI page -> triggers a command -> creates the job (copied the from Logging and DocumentOcr)

But thats totally unrelated :)
