### ISSUE TITLE
QuestPDF Fonts (docs)

### ISSUE THREAD

**Issue by jochem4207** [neozhu/CleanArchitectureWithBlazorServer#456]
Hey Guys,

This is more to inform / ask. It can be that i'm a little bit behind on the repo but when I use the export function on the product page (after setting the key) it crashed because it was not able to find the font `simhei`. I'm running windows 11. I changed it to `calibri` which is as far as I know a really basic font and it works just fine. I probably need to install the simhei font but I think if that's the case it should be in the readme.

Many thanks, still loving it and going to the moon with this repo 🚀

**Comment by neozhu** [comment]
@jochem4207 
Thank you for your feedback. the Calibri font works well for English content. However, if the content includes Chinese characters, the SimHei font is necessary. I agree that this is an important detail that should be included in the readme. We appreciate your suggestion and will make sure to update the documentation accordingly.

Keep enjoying the repo and let's continue our journey to the moon! 🚀

**Comment by neozhu** [comment]
the new version no longer uses the SimHei font.
