### ISSUE TITLE
CodeGen CLI?

### ISSUE THREAD

**Issue by bakes82** [neozhu/CleanArchitectureWithBlazorServer#476]
Can there be a CLI for the code gen?  I don't use VS, I use Rider.

**Comment by neozhu** [comment]
Hi bakes82, sorry, but I'm not familiar with the Rider development environment and CLI Mode. 
I can't offer specific recommendations for Rider.

**Comment by bakes82** [comment]
I mean make it a console / cli app that way it supports more than visual studio.

**Comment by neozhu** [comment]
sorry, I don't know how to develop dotnet CLI extensions, as I don't have knowledge in that area.
