### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by bakes82** [neozhu/CleanArchitectureWithBlazorServer#477]
How can we disable Hangfire?  - We've use hangfire in the past and it hasn't worked well for us, I would like to disable it, usually there is a setting in the appsettings.  Ideally should be its own project not tied to the UI so you can scale up/out with it.

Auth options (google/ms) - Is there no config options to disable these?  Dont I need to set a ClientId/Secret for microsoft/AAD?  Where?  Again should be tied to appsettings options if not enabled dont show the options.

Tenants - Not sure what this is doing, can you login to a different tenant?  Database per tenant?  When you login what tenant are you in, what tenant are the "products" associated with, pick lists are system level or tenant?  There seems to be a disconnect between the demo/tenants or its not implemented.

Logs - This appears empty, I do see a log file though

Quick look thru the code there seems to be a bunch of random //ToDo: impementing xxxx   (These seem implemented, so why are they todos?)

In ProductsPaginationQuery.cs there is a comment of //the currently logged in user on a .ToString that shows the filters applied.
The same file has unused localizer.

Date filters - you seem to be converting to string and the back to datetime for some reason.
```c#
DateTime today = DateTime.Now.Date;
DateTime start = today;  // this is already 00:00:00 for the date
DateTime end = today.AddDays(1).AddTicks(-1);  // 23:59:59.9999999 for the date
DateTime last30day = today.AddDays(-30);  // this is already 00:00:00 for the date 30 days ago
```

Not sure if VS has the same inspections as Rider but rider is showing a bunch of warning that could easily be cleaned up.  Rider also offers free licenses for open source projects.
![image](https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/3197191/a66da7cd-20c7-4ec0-af4e-fcf91f753d28)

**Comment by neozhu** [comment]
How can we disable Hangfire?
Yes, you can, 
comment out below code
` <PackageReference Include="Hangfire.AspNetCore" Version="1.8.4" />`
` <PackageReference Include="Hangfire.InMemory" Version="0.5.1" />`
`.AddHangfireService()`
`app.UseHangfireDashboard("/jobs", new DashboardOptions
        {
            Authorization = new[] { new HangfireDashboardAuthorizationFilter() },
            AsyncAuthorization = new[] { new HangfireDashboardAsyncAuthorizationFilter() }
        });`

Auth options (google/ms) - Is there no config options to disable these?
Sorry, there's no option to disable Google or MS auth. You can only remove the buttons and the related code

Tenants - Not sure what this is doing, can you login to a different tenant? Database per tenant?
Tenants here don't support multiple databases. It's just a parameter for user logins and used to query data, not real multi-tenancy.


Logs - This appears empty, I do see a log file though
logs can only be written to MS SQL or PostgreSQL databases, not SQLiteDB.

Quick look thru the code there seems to be a bunch of random //ToDo: impementing xxxx (These seem implemented, so why are they todos?)
Those '//ToDo: implement xxxx' comments were automatically generated by a code template tool. While they might seem implemented, the code still needs to be refactored based on specific requirements. I'm open to suggestions on how to better alert developers that these parts need to be modified according to actual needs.


the end, Thanks for pointing out the warnings in Rider. When I have time, I'll do some refactoring and optimization of the code to address these issues.

**Comment by bakes82** [comment]
The todos are fine for code generation files.  But your example base installed files shouldn’t have them I wouldn’t think.

An option to create a mostly blank install could be useful with just like auth and admin/role.  Also using appsettings to toggle options would be great.  Adding some readmes about what multi tenant and the other features might help others too.  Any plans to add multi db support?

**Comment by neozhu** [comment]
Thanks for the suggestions, @bakes82 . I agree with your ideas about the todos and installation files. A blank install with basic features and using appsettings to toggle options are great ideas. Regarding multi-database support, it's on my list to consider. Would you be interested in contributing a PR for these improvements? I'd love more community involvement.

**Comment by bakes82** [comment]
I made a console app generator here:  It uses the same templates you had, I just refactored it to use Type.  But this way as a console app, people can add their own templates, or can be enhanced more easily like if you wanted to generate files from database first, plus its not dependent on VS.
https://github.com/bakes82/CleanArchitectureWithBlazorServer/tree/main/src/CodeGenerator

There needs to be more documentation, also the code generator doesnt create all the files needed.  Things missing context, permissions, some code has hard defined fields that might not exist EX: Name if you look at the AdvancedSpecification.cs.txt (Id assume this should also generate clauses for every field on the object but it doesnt its just hard coded)

I think if you can make a branch with just the "base" no example models, and then if you can write up the steps to make a new entity and then write templates (or reference an example) for each step it would be a great starting point because right now the lacking documentation is a bit confusing

**Comment by neozhu** [comment]
Thanks for sharing the console app generator. However, I believe it's not suitable for other projects due to many dependencies. It might not be necessary to use this template for new projects, especially with the current lack of documentation and other issues.
