### ISSUE TITLE
[Bug] Navigation doesnt update on full load

### ISSUE THREAD

**Issue by bakes82** [neozhu/CleanArchitectureWithBlazorServer#497]
The nav bar needs to be refactored to implement "expanding" the mud nodes if the "current" page is under its node.
 
The MudNavGroup needs the "expand" set to true
https://github.com/neozhu/CleanArchitectureWithBlazorServer/blob/c439ccad75bb39b64fbcc48d5fc4576c50ebfed1/src/Blazor.Server.UI/Components/Shared/SideMenu.razor#L93C1-L93C1

Looks like you will need to make a new method that takes in the url from the NavigationManager and loop over the hrefs for the items under the navgroup.

Also I would of though the file named "navmenu" would be the primary navbar, but its actually SideMenu, Id also suggest reaming the "NavMenu" -> "HeaderMenu" and "SideMenu" -> "NavigationMenu"

SideMenu also has some weird things like its hiding/showing divs when closed.  Didnt make sense to me since its closed.
Also why are menu items "features"?

Im also a fan of interfaces and not doing more work so I had chatgpt spit out this concept out real quick.  What you think about this way, it moves more stuff to the pages where you do work, and dont then need to try and make the navItem in the nested spaghetti.

### 1. Define the `INavigablePage` Interface

```csharp
public interface INavigablePage
{
    string Title { get; }
    string Route { get; }
    Type ParentPageType { get; }
}
```

### 2. Implement the Interface on Desired Pages

For the parent:

```csharp
@page "/parent"
@implements INavigablePage

@code {
    public string Title => "Parent Page";
    public string Route => "/parent";
    public Type ParentPageType => null;  // No parent for the top-level page
}
```

For the child:

```csharp
@page "/child"
@implements INavigablePage

@code {
    public string Title => "Child Page";
    public string Route => "/child";
    public Type ParentPageType => typeof(ParentPage);  // Reference the parent page type directly
}
```

### 3. Build the Service to Discover Pages

```csharp
public class NavigablePageService
{
    public IEnumerable<Type> GetTopLevelPages()
    {
        var assembly = Assembly.GetExecutingAssembly();
        return assembly.GetTypes().Where(type => 
            typeof(INavigablePage).IsAssignableFrom(type) 
            && !type.IsInterface 
            && ((INavigablePage)Activator.CreateInstance(type)).ParentPageType == null);
    }

    public IEnumerable<Type> GetChildPages(Type parentPageType)
    {
        var assembly = Assembly.GetExecutingAssembly();
        return assembly.GetTypes().Where(type => 
            typeof(INavigablePage).IsAssignableFrom(type) 
            && !type.IsInterface 
            && ((INavigablePage)Activator.CreateInstance(type)).ParentPageType == parentPageType);
    }
}
```

### 4. Render Parent-Child Navigation in Blazor

```razor
@inject NavigablePageService PageService

<nav>
    @foreach (var parentType in PageService.GetTopLevelPages())
    {
        var parentInstance = (INavigablePage)Activator.CreateInstance(parentType);
        <a href="@parentInstance.Route">@parentInstance.Title</a>
        <ul>
            @foreach (var childType in PageService.GetChildPages(parentType))
            {
                var childInstance = (INavigablePage)Activator.CreateInstance(childType);
                <li><a href="@childInstance.Route">@childInstance.Title</a></li>
            }
        </ul>
    }
</nav>
```

**Comment by neozhu** [comment]
Please don't make the code too complicated. You wouldn't have had this issue if it was your first PR. I'm now using the code you provided the first time, and it's working well.

**Comment by bakes82** [comment]
Issues with what, the current code is broken.... If you load a page that's not the "home" page the expand doesnt open.  Has nothing to do with my load screen PR.  


You can see here: 
http://106.52.105.140:6101/pages/products

**Comment by neozhu** [comment]
@bakes82 

Thanks for your suggestions. I have renamed the navigation menus as you suggested. Please take a look this PR #502 and let me know if you have any other feedback.

I am not sure what you mean by "Parent-Child Navigation in Blazor". Could you please explain it to me or submit a PR?

Thanks,

**Comment by Bram1903** [comment]
@bakes82, could you check #502, and let us know if you have anything to add? Otherwise we'll merge it to main.

**Comment by Bram1903** [comment]
@neozhu, the PR you submitted in #502, only addresses some naming changes, not the reason this PR got created as @bakes82 mentioned in a comment on that PR. I don't think we should close this issue because we merged that naming change PR.
