### ISSUE TITLE
Initial Slow Database Query on Non-Identity Pages Warnings

### ISSUE THREAD

**Issue by Bram1903** [neozhu/CleanArchitectureWithBlazorServer#504]
**Issue: Initial Slow Database Query on Non-Identity Pages**

**Description:**
When launching the application and navigating to pages that retrieve data from the database but do not utilize the Identity services (specifically, the Users and Roles pages), a warning message appears in the console indicating that the request took an unusually long time to complete. This delay seems to stem from the initial connection setup, as subsequent requests, such as page refreshes, perform significantly faster.

![Screenshot 2023-09-01 at 14 26 46](https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/70259613/cbf82925-22b4-4837-a9f3-06471a308f24)

**Solution Required:**
We need to identify and implement a solution to mitigate this initial slowdown when querying the database for the first time. The goal is to ensure that database queries on these pages are consistently fast, even on the initial load.

**Steps to Reproduce:**
1. Launch the application.
2. Navigate to any non-identity-related page that queries data from the database.
3. Observe the warning message in the console indicating the slow initial request.

**Expected Outcome:**
The initial database queries on non-identity pages should not exhibit a significant delay, providing a smooth user experience from the moment the application is launched.

**Comment by neozhu** [comment]
Hi Bram,

I understand that you believe this issue is related to Identity services. However, I do not think this is the case. The slow initial database query is likely due to the application's startup and initialization[warm-up] process. When the application is first launched

**Comment by Bram1903** [comment]
Hey Neozhu,

I appreciate your response, but I want to clarify that there seems to be a misunderstanding regarding the nature of the issue. It is unrelated to Identity pages; rather, it specifically pertains to pages where we query data from the database using our own `ApplicationDbContext`. This issue does not have any connection to the Identity services.

The observed delay in the initial database query appears to be related to the warm-up process during the application's startup. The application takes some time to establish connections and prepare itself when launched for the first time, which affects the pages that interact with the database directly.

I think we should try and find a solution where we can solve this initial warmup problem. 

Kind regards,
Bram

**Comment by Bram1903** [comment]
@neozhu, I've tried a few things to see if database warmups would solve the issue. However, the solutions I've tested are inconsistent and not very practical. So, I'm thinking of a different approach: we could ignore measuring the duration of the first three requests.

The reason is that these initial requests aren't like what real users would do. They take longer because the application is starting up. By not counting them, we can focus on measuring the performance of actual user actions.

I'd like to know what you think about this idea and if it makes sense to you.

**Comment by neozhu** [comment]
@Bram1903 
Thanks for proposing this idea.
I suggest we try out your approach first to see how it works. If it works well, we can merge it to the master branch.

**Comment by Bram1903** [comment]
> @Bram1903
> Thanks for proposing this idea.
> I suggest we try out your approach first to see how it works. If it works well, we can merge it to the master branch.

I created a pull request (see #509). Check it out, and let me know what your thoughts are.
