### ISSUE TITLE
Parent - child issue

### ISSUE THREAD

**Issue by Stonne** [neozhu/CleanArchitectureWithBlazorServer#527]
Hi 
When you change the tenant name in tenants the new name is not reflected in the user profile.. Because (in my opininion) the setup of the user does not reflect the relation with the tenant.    
Shouldn't there be something like     public virtual Tenant Tenant {get; set; } = default!  in the ApplicationUser.cs file 
Am I right ?
Best regs

**Comment by neozhu** [comment]
Yes, you're right. I didn't consider using a foreign key to associate the Tenant object at that time because the Tenant isn't part of 'Identity.EntityFrameworkCore'. I'm not sure if I can directly add the Tenant property in ApplicationUser, but I'll give it a try.
