### ISSUE TITLE
Blazor server rendering upgrade

### ISSUE THREAD

**Issue by amalsharief** [neozhu/CleanArchitectureWithBlazorServer#528]
Hi, 
Is there a branch for upgrading the template to .net 8 blazor web
thanks,

abdo

**Comment by neozhu** [comment]
Yes, once .NET 8 is officially released, I'll be upgrading the template to .NET 8 Blazor Web.

**Comment by nadeemshaikhdev** [comment]
Hi any update on the .NET 8 upgrade.

**Comment by Bram1903** [comment]
> Hi any update on the .NET 8 upgrade?

Hello,

See #554 for the latest state of our transition to .NET 8.
Since .NET 8 doesn't bring any major breaking changes the transition should be quite smooth and easy!

Kind regards,
Bram
