### ISSUE TITLE
Consider adding component tests and end-2-end test

### ISSUE THREAD

**Issue by egil** [neozhu/CleanArchitectureWithBlazorServer#529]
For testing component logic, the template should include a bUnit test project (or amend the unit testing project to include a reference to bunit), which makes it possible to test components in isolation like with https://bunit.dev.

For end-2-end rendering, a [playwright](https://playwright.dev/dotnet/) project should be added.

**Comment by neozhu** [comment]
Hi @egil,

Thank you for the suggestions! 🚀 Could you please create a PR with these enhancements? It would be great to review and discuss your proposed changes directly.

Looking forward to your contribution!

Best,
Hualin
