### ISSUE TITLE
hello Bram1903

### ISSUE THREAD

**Issue by neozhu** [neozhu/CleanArchitectureWithBlazorServer#547]
@Bram1903, I'll be going to Germany on November 3rd and will stay in Heidenheim for 45 days. I'm not sure how far it is from you. If it's close, maybe we can meet up

**Comment by Bram1903** [comment]
Hey @neozhu ,

That would be fun, however I just looked up Heidenheim, and it's almost 800km from where I live 🙁

Otherwise I would definitely have meet up with you!

**Comment by neozhu** [comment]
Indeed, it's quite a distance. Looks like we'll have to stick to online communication for now. However, I was hoping to explore a bit during this trip. Hopefully, we'll have a chance to meet in person in the future!
