### ISSUE TITLE
Community (Discord) like?

### ISSUE THREAD

**Issue by amalsharief** [neozhu/CleanArchitectureWithBlazorServer#548]
Hi, 
Thank you for the brilliant work. 
Is there an official place for documentation or to ask questions (how to do?).
Thank you in advance.

**Comment by neozhu** [comment]
Thank you for your kind words. Currently, we don't have official documentation. I'd recommend trying to debug on your own for now. If you have further questions or encounter any issues,

**Comment by neozhu** [comment]
You can try adjusting the value of 'ExpirationMinutes' in the image below to control the token's validity period. This is the simplest method
<img width="920" alt="image" src="https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/1549611/cf411452-b024-4f19-9b65-deca0c31d5df">

**Comment by Bram1903** [comment]
@neozhu If you want, we can set up a Discord server, however, I'm not sure if you can use Discord.

**Comment by neozhu** [comment]
> @neozhu If you want, we can set up a Discord server, however, I'm not sure if you can use Discord.

Thanks for the offer! I can access Discord, but I believe GitHub issues should suffice for our purposes.
