### ISSUE TITLE
IsLive not updating on external login ,also no logic on logout making islive as false.

### ISSUE THREAD

**Issue by nammadhu** [neozhu/CleanArchitectureWithBlazorServer#549]
[JSInvokable]
 public async Task ConfirmExternal(string provider, string userName, string name, string accessToken)
 {
     var user = await CreateUserWithExternalProvider(provider, userName, name, accessToken);
     await TokenProvider.Login(user);
    // var res=UserManager.UpdateIsLive(userId: user.Id,  true); //this is missing
     NavigationManager.NavigateTo(NavigationManager.Uri, true);
     Logger.LogInformation("{@UserName:l} has successfully logged in", userName);
 }

**Comment by neozhu** [comment]
Thank you for pointing this out. Regarding the isLive field, we've stopped using it. We are now determining user online status via SignalR, rather than through login and logout actions. So, the absence of the related logic aligns with our current design.
