### ISSUE TITLE
Starting in language other than english

### ISSUE THREAD

**Issue by amalsharief** [neozhu/CleanArchitectureWithBlazorServer#551]
Hi, what is the best way to start the application in a language and direction other than English, for example RTL  languages

Thank you in advance.

**Comment by Bram1903** [comment]
Hello, 

Everyone can set their language, however, if you want to change the default language that is being applied on the first startup, you could modify the `LocalizationConstants` class which can be found in the `CleanArchitecture.Blazor.Infrastructure.Constants.Localization` namespace in the file named [LocalizationConstants](https://github.com/neozhu/CleanArchitectureWithBlazorServer/blob/main/src/Infrastructure/Constants/Localization/LocalizationConstants.cs). At the top of that file, you find:

```csharp
public static readonly LanguageCode[] SupportedLanguages =
    {
        new()
        {
            Code = "en-US",
            DisplayName = "English"
        },
        new()
        {
            Code = "nl-NL",
            DisplayName = "Nederlands"
        },
        new()
        {
            Code = "de-DE",
            DisplayName = "Deutsch"
        },
        new()
        {
            Code = "fr-FR",
            DisplayName = "French"
        },
        new()
        {
            Code = "es-ES",
            DisplayName = "Spanish"
        }
    };
```

Move the language you want to be used by default to the top, where currently English is defined. The first language in this array is what is being used by default as shown in the `ApplicationBuilderExtensions` on line 30 which can be found [here](https://github.com/neozhu/CleanArchitectureWithBlazorServer/blob/main/src/Infrastructure/Extensions/ApplicationBuilderExtensions.cs).

**Comment by Bram1903** [comment]
Hello, 

What might be the issue here is that we save your preference in your browser storage. You could clear that, and see if it then starts up with another language as default. You can also test this behavior by visiting the website in a private window.

![image](https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/70259613/e070c59e-c9db-4ded-a817-4b392395156a)

Kind regards,
Bram

**Comment by neozhu** [comment]
> I am using Chrome, mine looks like
> 
> ![image](https://user-images.githubusercontent.com/5045490/281271437-efb4ba6a-67fe-4940-b826-e39dfc2d88b0.png)
> 
> I am using the latest version of the template. userPreferences is not shown. Any hint?

You can try changing the current language and color theme, and it will appear. If no changes are made, the system does not need to store any information by default.

**Comment by Bram1903** [comment]
> Does .aspnetcore .culture cookie have a relation to my problem? as it contains en-US
> 
> ![image](https://user-images.githubusercontent.com/5045490/281457069-9501fdfd-d9a9-440a-b4cc-d0ad4a2f7c2b.png)

Whoops, you are right! We store that into cookies rather than the local storage. That's my fault haha. Remove that record, and reload, it should then automatically apply the default language based on my first response!

**Comment by neozhu** [comment]
there is 
<img width="747" alt="image" src="https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/1549611/8f6746ad-2bb9-4473-a81e-97738fea6a7d">
