### ISSUE TITLE
Congratulations on 500 stars ✨

### ISSUE THREAD

**Issue by Bram1903** [neozhu/CleanArchitectureWithBlazorServer#552]
Hey, 

Congrats on the 500 stars on this repository! I think that's quite a milestone you can be proud of 💪🏻

To many more 🥂

**Comment by jochem4207** [comment]
Congrats @neozhu & @Bram1903, i've been a bit afk due the project not getting attention, going to look at all stuff you guys upgraded. Thank you so much for this project <3 

At 1000 stars we get a donate button?
