### ISSUE TITLE
UserManager resolving

### ISSUE THREAD

**Issue by AndreyBezzub** [neozhu/CleanArchitectureWithBlazorServer#555]
Hi,

What is the reason for using the ServiceProvider to get a UserManager instance in a scoped service like IdentityService? I do understand this approach in services that are registered as singletons (PicklistService, UserDataProvider, TenantService), but in a scoped service, wouldn't it be better to inject the UserManager (which is a scoped service) via the constructor?

**Comment by neozhu** [comment]
It is necessary to use `scopeFactory.CreateScope()` to create a new instance of `UserManager<ApplicationUser>` within a new scope. The reason is that `ApplicationDbContext` must be managed with a Transient lifecycle, whereas `UserManager<ApplicationUser>` is by default managed with a Scoped lifecycle. This creates a conflict, so it's essential to use the above method to create a new instance in a new scope. I'm not sure if my explanation is entirely correct, but I have tried the method you mentioned, and the system throws an error.

**Comment by MatteoZampariniDev** [comment]
Oh I see, but why the IApplicationDbContext is registered with a transient lifetime? I think that's quite unsafe.

https://learn.microsoft.com/en-us/ef/core/dbcontext-configuration/#implicitly-sharing-dbcontext-instances-via-dependency-injection

**Comment by AndreyBezzub** [comment]
>The reason is that `ApplicationDbContext` must be managed with a Transient lifecycle, whereas `UserManager<ApplicationUser>` is by default managed with a Scoped lifecycle.
Thanks @neozhu for the explanations. It became clear to me where the need for such an implementation came from.
But, as @MatteoZampariniDev mentioned,  it's not clear, what's the reason for registering `ApplicationDbContext` as transient? According to MS, in most ASP.NET Core apps, it's safe from concurrent issues to register a DbContext as scoped. I'm wondering what forced you to switch to using DbContext as transient? You might face a concurrent access issue, but a quick search in code for signs of explicit parallel execution of multiple threads did not give any results.

**Comment by neozhu** [comment]
Thanks for bringing this up. It's important to recognize that Blazor Applications and Web (API/MVC) Applications operate differently. When using a scoped DbContext in a Blazor Application, you might encounter issues, especially when multiple users are online and attempting to modify the same entity object simultaneously. This can lead to conflicts. In a Blazor scenario, managing DbContext as transient helps to avoid such conflicts by ensuring that each operation gets its own instance, thereby reducing the risk of concurrent access issues. This approach might be different from the typical ASP.NET Core apps, but it's tailored to suit the unique demands and operational patterns of Blazor Applications.
