### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by carlsixsmith** [neozhu/CleanArchitectureWithBlazorServer#557]
Is it safe storing an authentication token in local storage? One could just grab the token and re-use it, or malicious JavaScript could read it.?

How are people using this template mitigating this risk?

**Comment by neozhu** [comment]
There's no need to worry about the security of token storage in this case. First, the token is encrypted before being stored locally. Additionally, this project does not offer any web APIs, meaning that the token is solely used for login purposes.

**Comment by Bram1903** [comment]
> The issue isn't encryption. You can just lift the encrypted token out of local storage (fully accessible via JavaScript) and then you are logged in as the user.

Hello Carl,

Managing user authentication securely is indeed crucial, and I appreciate your concern about storing tokens in the client's browser. It's a common challenge faced by many applications.

Your observation about the vulnerability of tokens stored in local storage is valid, and it's something that even large clients like Discord encounter. While we can't entirely prevent users from copying the token, we can take steps to enhance security.

One approach to consider is transitioning from local storage to [http-only cookies](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#). This move prevents JavaScript from directly accessing the token's value and adds an extra layer of security. @neozhu, this could be a potential solution worth exploring.

However, Neozhu, I find myself overwhelmed with work, juggling responsibilities from both University and my company. Regrettably, I'm unable to carve out the time needed to assist with the implementation of this solution. I understand you likely have a full plate as well. Please let me know if you're open to exploring this further on your end!

Kind regards,
Bram
