### ISSUE TITLE
Page error in entering a invalid address.

### ISSUE THREAD

**Issue by linkxu1989** [neozhu/CleanArchitectureWithBlazorServer#56]
Describe the bug
See logs in the screenshot.

To Reproduce

Go to "https://localhost:44375/pages"
Refresh the page.
See console logs.
Click "Product" page, data could not be loaded.
Expected behavior
Clean the error.

Screenshots
![image](https://user-images.githubusercontent.com/17608441/158999463-8d26f2fd-9863-486a-9757-698e74d0997c.png)

Additional context
No

**Comment by neozhu** [comment]
I refactored the code to avoid this problem, but it didn't solve it.
refer to this https://github.com/dotnet/aspnetcore/issues/18340

**Comment by neozhu** [comment]
![image](https://user-images.githubusercontent.com/1549611/159000276-b3809c2a-d7dd-4cc1-818c-c93255f81d16.png)

**Comment by linkxu1989** [comment]
Why not rendering to the home page directly in case of the error? It is much easier probably.

**Comment by linkxu1989** [comment]
I'm try to use the solution https://github.com/dotnet/aspnetcore/issues/33336#issuecomment-862425579

It works, after changing: NotificationsService.

 private async Task<DateTime> GetLastReadTimestamp()
    {
        try
        {
            var timestamp = await _localStorageService.GetItemAsync<DateTime>(LocalStorageKey);
            return timestamp;
        }
        catch (Exception ex) when (ex.GetType().Name == "JSDisconnectedException")
        {
            return DateTime.MinValue;
        }
        
    }

**Comment by linkxu1989** [comment]
Looks like it have been fixed, correct?

**Comment by linkxu1989** [comment]
This is not happening on chrome but edge.

**Comment by neozhu** [comment]
I refactor IdentityAuthenticationService.cs  code.

**Comment by linkxu1989** [comment]
Nice
