### ISSUE TITLE
Make role management against multi tenant and tenant separation

### ISSUE THREAD

**Issue by nammadhu** [neozhu/CleanArchitectureWithBlazorServer#561]
Hi @neozhu ,
Please try making Make role management against multi tenant and tenant separation. So multiple organizations can use the same app with separation ,then it will be a great project with all white labelling and all kind of.

**Comment by Alywan** [comment]
LOL. I was just entering here to write exactly the same thing :))

**Comment by jochem4207** [comment]
It's already quite a great project (especially for something free). As mentioned in most issues, you can also submit a PR

**Comment by neozhu** [comment]
I appreciate your feedback and encourage everyone to contribute to the project. I will continue to work on it and make it even better.
