### ISSUE TITLE
Issue with authentication when application has restarted

### ISSUE THREAD

**Issue by cptzig** [neozhu/CleanArchitectureWithBlazorServer#569]
There is a bug that I have been trying to fix, but I cannot find what is going on. When you run the application and then you authenticate, if you stop the program and run again, then it does not go back to the same state, even though the authentication cookie has not been cleared and it should just read that cookie and authenticate. 

Below is the picture of the bug that I am trying to explain. 

![image](https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/42944941/92b38bef-41db-426b-a51b-4eecb1fbeef9)

**Comment by neozhu** [comment]
Are you using the latest version to debugging this issue? I remember the most recent submission should have fixed this problem.
