### ISSUE TITLE
[Bug] Logging Breaks in PostgreSQL: Naming Conventions Issue

### ISSUE THREAD

**Issue by Bram1903** [neozhu/CleanArchitectureWithBlazorServer#574]
### Problem
When utilizing PostgreSQL as the database provider in our project, the logging functionality appears to be dysfunctional. The issue doesn't produce any error messages, but after a thorough investigation, it seems to stem from the use of a naming convention library.

In particular, the problem arises in the `CleanArchitecture.Blazor.Infrastructure.DependencyInjection` class, specifically within the `UseDatabase` method. Here, snake naming conventions are enabled when PostgreSQL is used. Consequently, the table namings deviate significantly from expectations, causing Serilog to be unable to locate the correct table for logging.

### Root Cause
The source of the issue lies in the application of snake naming conventions exclusively when using PostgreSQL. This inconsistency in naming conventions is not aligned with the broader expectations of our solution.

### Possible Solutions
1. **Remove EFCore.NamingConventions Library**
   - Eliminate the `EFCore.NamingConventions` library from the project.
   - Remove the line `.UseSnakeCaseNamingConvention()` in the `UseDatabase` method.

2. **Modify Table Names in SerilogExtensions**
   - Adjust table names in the `CleanArchitecture.Blazor.Infrastructure.Extensions.SerilogExtensions` class, specifically within the `WriteToNpgsql` method.

### Additional Context
It might be beneficial to reconsider the rationale behind applying snake case conventions exclusively for PostgreSQL. This might introduce unexpected behavior across the entire solution.

### Screenshots
Screenshot of the PostgreSQL database, showcasing the table names when snake case conventions are applied.

![PostgreSQL Database](https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/70259613/4c5771b2-1f53-4ea5-bca4-f98e33e46a51)

This issue is crucial for maintaining a consistent and reliable logging system across different database providers.

**Comment by Bram1903** [comment]
> Here, you can redefine the field names mapped in the database.

I appreciate the suggestion to modify field names in the SeriLogExtension, and I've already included that as one of the proposed solutions in the issue description. What I'm specifically seeking clarification on is our preference – do we want to proceed with remapping the field names, as suggested, or are we leaning towards abandoning the snake case convention altogether? It's worth noting that currently, we enable snake casing exclusively when using PostgreSQL, which might be contributing to the inconsistency. I'd like to understand the preferred approach before implementing any changes.

**Comment by neozhu** [comment]
The reason we use snake case conversion in PostgreSQL is because by default, the table names and field names created by Entity Framework (EF) are not directly queryable with SQL. This issue is not unique to PostgreSQL but is also present in Oracle and other case-sensitive databases. In other words, if we don't perform a name conversion, we must enclose table names and field names in double quotes when querying with SQL to ensure proper recognition.
