### ISSUE TITLE
Latest works fine but dotnet new is broke ? 

### ISSUE THREAD

**Issue by punkouter24** [neozhu/CleanArchitectureWithBlazorServer#576]
Any idea what this is about ? 

![image](https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/121304072/4718980f-7762-4e71-bb92-5fcb65fd9a96)

1>------ Build started: Project: Server.UI, Configuration: Debug Any CPU ------
1>C:\Users\punko\Downloads\Cawbs\src\Server.UI\Pages\Dashboard\Dashboard.razor(211,5,211,100): warning RZ10012: Found markup element with unexpected name 'LandingSection'. If this is intended to be a component, add a @using directive for its namespace.
1>C:\Users\punko\Downloads\Cawbs\src\Server.UI\Pages\Products\Components\ProductFormDialog.razor(1,14,1,20): error CS0234: The type or namespace name 'Server' does not exist in the namespace 'Blazor' (are you missing an assembly reference?)
1>C:\Users\punko\Downloads\Cawbs\src\Server.UI\Pages\Identity\Users\Profile.razor(2,14,2,20): error CS0234: The type or namespace name 'Server' does not exist in the namespace 'Blazor' (are you missing an assembly reference?)
1>Done building project "Server.UI.csproj" -- FAILED.
2>------ Build started: Project: Application.IntegrationTests, Configuration: Debug Any CPU ------
3>------ Build started: Project: docker-compose, Configuration: Debug Any CPU ------
2>CSC : error CS0006: Metadata file 'C:\Users\punko\Downloads\Cawbs\src\Server.UI\obj\Debug\net8.0\ref\Cawbs.Server.UI.dll' could not be found
2>Done building project "Application.IntegrationTests.csproj" -- FAILED.
3>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4911,5): error MSB3030: Could not copy the file "C:\Users\punko\Downloads\Cawbs\src\Server.UI\bin\Debug\net8.0\Cawbs.Server.UI.dll" because it was not found.
3>Done building project "docker-compose.dcproj" -- FAILED.
========== Build: 0 succeeded, 3 failed, 9 up-to-date, 0 skipped ==========
========== Build completed at 12:20 PM and took 02.491 seconds ==========

**Comment by neozhu** [comment]
The issue seems to be that the dependent third-party library was not loaded successfully from NuGet. You can try clean and then rebuild on this project or delete the bin directory under the solution directory and then rebuild.
