### ISSUE TITLE
AuditTrails and Logs

### ISSUE THREAD

**Issue by cptzig** [neozhu/CleanArchitectureWithBlazorServer#583]
Is it a known bug that AuditTrails and Logs are not displaying? The functionality seems to be there, but I have not investigated further why is not showing any logs or audit trails.

**Comment by neozhu** [comment]
Please pull the latest code. You may also need to run 'add-migration xxx' and 'update-database'

**Comment by cptzig** [comment]
@neozhu I have made some changes that you can see at #602, please take a look and let me know if you think that I need to make some changes.
