### ISSUE TITLE
Adding entity does not allow routing to that page due to permissions

### ISSUE THREAD

**Issue by jeffrosenthal** [neozhu/CleanArchitectureWithBlazorServer#587]
This is more of a question than bug list issue... sorry

I added a new entity and used the Add Feature scaffold (very nice)

The Name of my entity is CaseCategory. I did the add migration and it shows in my database. (Good)

In my CaseCategory razor - when the line " @attribute [Authorize(Policy =Permissions.CaseCategories.View)] " is in place - my routing to the page sends me back to the home page (stating I am already logged in)
If I remove the parameter leaving just [Authorize] it works fine.
I Added the permissions 
`    [DisplayName("CaseCategories")]
    [Description("CaseCategories Permissions")]
    public static class CaseCategories
    {
        public const string View = "Permissions.CaseCategories.View";
        public const string Create = "Permissions.CaseCategories.Create";
        public const string Edit = "Permissions.CaseCategories.Edit";
        public const string Delete = "Permissions.CaseCategories.Delete";
        public const string Search = "Permissions.CaseCategories.Search";
        public const string Export = "Permissions.CaseCategories.Export";
        public const string Import = "Permissions.CaseCategories.Import";
    }
`
and also in PermissionModules.cs

I believe I am missing something but need assistance please. Could someone point me in the right direction?

I am logged in as Admin. Is there a policy claim or role that I need to adjust?

**Comment by jeffrosenthal** [comment]
edited text

**Comment by neozhu** [comment]
It appears that you might need to set permissions for the role and account to include the new permissions (Permission) that you've defined. After assigning these new permissions to the appropriate roles or accounts, make sure to log out and then log back in. This should allow the authorization attributes to work correctly with the newly added permissions.
I hope this helps you.
<img width="229" alt="image" src="https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/1549611/f5ee2830-8a9b-489d-831e-cddbd2b53921">

<img width="201" alt="image" src="https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/1549611/cc55a5fc-c86e-4b81-928c-4c3e747d19ff">

**Comment by jeffrosenthal** [comment]
Thank you for the reply.  I thought this too but all of those permissions are unchecked for administrators so I thought there was so sort of admin override. For example,  Products works just fine but all the permissions are unchecked in admin.I will try this. Thank you. 
-------- Original message --------From: "neo.zhu" ***@***.***> Date: 1/20/24  10:12 PM  (GMT-05:00) To: neozhu/CleanArchitectureWithBlazorServer ***@***.***> Cc: jeffrosenthal ***@***.***>, Author ***@***.***> Subject: Re: [neozhu/CleanArchitectureWithBlazorServer] Adding entity does not allow routing to that page due to permissions (Issue #587) 
It appears that you might need to set permissions for the role and account to include the new permissions (Permission) that you've defined. After assigning these new permissions to the appropriate roles or accounts, make sure to log out and then log back in. This should allow the authorization attributes to work correctly with the newly added permissions.
I hope this helps you.
image.png (view on web)
image.png (view on web)

**Comment by jeffrosenthal** [comment]
I just tried editing the permissions for Admin - adding (checking the boxes) for my new entity. After logging out and back in - **it works**. This however raises the question as to _why are the other entities (ie products) able to be viewed as Administrator while they are not permissions set?_ 
It seems that there is, or at least the behavior observed, is such that Administrator has global access and does not see the individual permissions at least for template provided entities. 
What am I missing?

**Comment by neozhu** [comment]
![image](https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/1549611/c973e014-2b21-4861-89c0-b59db5434941)
there is the project initialization, all permissions were added by default to the admin group.
