### ISSUE TITLE
Anyone add a feature using the vs2022 ? Does not work for me

### ISSUE THREAD

**Issue by punkouter24** [neozhu/CleanArchitectureWithBlazorServer#608]
Created a simple domain class

public class Bugger : BaseAuditableEntity
{
    public string? NameBug { get; set; }
    public string? DescriptionBug { get; set; }
}

Rt click Application/Features

Select Bugger.cs

Creates alot of code and it is broke.

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	CS0234	The type or namespace name 'Buggers' does not exist in the namespace 'CleanArchitecture.Blazor.Application.Features' (are you missing an assembly reference?)	Server.UI	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Server.UI\Pages\Buggers\Buggers.razor	10	Active	
Error	CS0234	The type or namespace name 'Buggers' does not exist in the namespace 'CleanArchitecture.Blazor.Application.Features' (are you missing an assembly reference?)	Server.UI	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Server.UI\Pages\Buggers\Buggers.razor	4	Active	
Error	CS0234	The type or namespace name 'Buggers' does not exist in the namespace 'CleanArchitecture.Blazor.Application.Features' (are you missing an assembly reference?)	Server.UI	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Server.UI\Pages\Buggers\Buggers.razor	5	Active	
Error	CS0234	The type or namespace name 'Buggers' does not exist in the namespace 'CleanArchitecture.Blazor.Application.Features' (are you missing an assembly reference?)	Server.UI	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Server.UI\Pages\Buggers\Buggers.razor	6	Active	
Error	CS0234	The type or namespace name 'Buggers' does not exist in the namespace 'CleanArchitecture.Blazor.Application.Features' (are you missing an assembly reference?)	Server.UI	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Server.UI\Pages\Buggers\Buggers.razor	7	Active	
Error	CS0234	The type or namespace name 'Buggers' does not exist in the namespace 'CleanArchitecture.Blazor.Application.Features' (are you missing an assembly reference?)	Server.UI	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Server.UI\Pages\Buggers\Buggers.razor	8	Active	
Error	CS0234	The type or namespace name 'Buggers' does not exist in the namespace 'CleanArchitecture.Blazor.Application.Features' (are you missing an assembly reference?)	Server.UI	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Server.UI\Pages\Buggers\Buggers.razor	9	Active	
Error	CS0234	The type or namespace name 'Buggers' does not exist in the namespace 'CleanArchitecture.Blazor.Application.Features' (are you missing an assembly reference?)	Server.UI	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Server.UI\Pages\Buggers\Buggers.razor	11	Active	
Error	CS0117	'Permissions' does not contain a definition for 'Buggers'	Server.UI	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Server.UI\Pages\Buggers\Buggers.razor	15	Active	
Error	CS0246	The type or namespace name 'BuggerDto' could not be found (are you missing a using directive or an assembly reference?)	Server.UI	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Server.UI\Pages\Buggers\Buggers.razor	204	Active	
Error	CS0246	The type or namespace name 'BuggerDto' could not be found (are you missing a using directive or an assembly reference?)	Server.UI	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Server.UI\Pages\Buggers\Buggers.razor	205	Active	
Error	CS0246	The type or namespace name 'BuggerDto' could not be found (are you missing a using directive or an assembly reference?)	Server.UI	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Server.UI\Pages\Buggers\Buggers.razor	206	Active	
Error	CS0246	The type or namespace name 'BuggersWithPaginationQuery' could not be found (are you missing a using directive or an assembly reference?)	Server.UI	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Server.UI\Pages\Buggers\Buggers.razor	220	Active	
Error	CS0246	The type or namespace name 'BuggerDto' could not be found (are you missing a using directive or an assembly reference?)	Server.UI	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Server.UI\Pages\Buggers\Buggers.razor	241	Active	
Error	CS0246	The type or namespace name 'BuggerDto' could not be found (are you missing a using directive or an assembly reference?)	Server.UI	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Server.UI\Pages\Buggers\Buggers.razor	241	Active	
Error	CS0246	The type or namespace name 'BuggerListView' could not be found (are you missing a using directive or an assembly reference?)	Server.UI	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Server.UI\Pages\Buggers\Buggers.razor	266	Active	
Error	CS0246	The type or namespace name 'BuggerDto' could not be found (are you missing a using directive or an assembly reference?)	Server.UI	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Server.UI\Pages\Buggers\Buggers.razor	317	Active	
Error	CS0246	The type or namespace name 'BuggerDto' could not be found (are you missing a using directive or an assembly reference?)	Server.UI	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Server.UI\Pages\Buggers\Buggers.razor	334	Active	
Error	CS0234	The type or namespace name 'Buggers' does not exist in the namespace 'CleanArchitecture.Blazor.Application.Features' (are you missing an assembly reference?)	Server.UI	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Server.UI\Pages\Buggers\Components\BuggerFormDialog.razor	1	Active	
Error	CS0246	The type or namespace name 'AddEditBuggerCommandValidator' could not be found (are you missing a using directive or an assembly reference?)	Server.UI	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Server.UI\Pages\Buggers\Components\BuggerFormDialog.razor	35	Active	
Error	CS0246	The type or namespace name 'AddEditBuggerCommand' could not be found (are you missing a using directive or an assembly reference?)	Server.UI	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Server.UI\Pages\Buggers\Components\BuggerFormDialog.razor	36	Active	
Error	CS0234	The type or namespace name 'Buggers' does not exist in the namespace 'CleanArchitecture.Blazor.Application.Features' (are you missing an assembly reference?)	Server.UI	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Server.UI\Pages\Buggers\Components\BuggersAdvancedSearchComponent.razor	1	Active	
Error	CS0246	The type or namespace name 'BuggersWithPaginationQuery' could not be found (are you missing a using directive or an assembly reference?)	Server.UI	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Server.UI\Pages\Buggers\Components\BuggersAdvancedSearchComponent.razor	20	Active	
Error	CS1061	'IApplicationDbContext' does not contain a definition for 'Buggers' and no accessible extension method 'Buggers' accepting a first argument of type 'IApplicationDbContext' could be found (are you missing a using directive or an assembly reference?)	Application	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Application\Features\Buggers\Commands\AddEdit\AddEditBuggerCommand.cs	51	Active	
Error	CS1061	'IApplicationDbContext' does not contain a definition for 'Buggers' and no accessible extension method 'Buggers' accepting a first argument of type 'IApplicationDbContext' could be found (are you missing a using directive or an assembly reference?)	Application	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Application\Features\Buggers\Commands\AddEdit\AddEditBuggerCommand.cs	63	Active	
Error	CS1061	'AddEditBuggerCommand' does not contain a definition for 'Name' and no accessible extension method 'Name' accepting a first argument of type 'AddEditBuggerCommand' could be found (are you missing a using directive or an assembly reference?)	Application	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Application\Features\Buggers\Commands\AddEdit\AddEditBuggerCommandValidator.cs	10	Active	
Error	CS1061	'IApplicationDbContext' does not contain a definition for 'Buggers' and no accessible extension method 'Buggers' accepting a first argument of type 'IApplicationDbContext' could be found (are you missing a using directive or an assembly reference?)	Application	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Application\Features\Buggers\Commands\Create\CreateBuggerCommand.cs	50	Active	
Error	CS1061	'CreateBuggerCommand' does not contain a definition for 'Name' and no accessible extension method 'Name' accepting a first argument of type 'CreateBuggerCommand' could be found (are you missing a using directive or an assembly reference?)	Application	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Application\Features\Buggers\Commands\Create\CreateBuggerCommandValidator.cs	11	Active	
Error	CS1061	'IApplicationDbContext' does not contain a definition for 'Buggers' and no accessible extension method 'Buggers' accepting a first argument of type 'IApplicationDbContext' could be found (are you missing a using directive or an assembly reference?)	Application	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Application\Features\Buggers\Commands\Delete\DeleteBuggerCommand.cs	39	Active	
Error	CS1061	'IApplicationDbContext' does not contain a definition for 'Buggers' and no accessible extension method 'Buggers' accepting a first argument of type 'IApplicationDbContext' could be found (are you missing a using directive or an assembly reference?)	Application	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Application\Features\Buggers\Commands\Delete\DeleteBuggerCommand.cs	44	Active	
Error	CS1061	'IApplicationDbContext' does not contain a definition for 'Buggers' and no accessible extension method 'Buggers' accepting a first argument of type 'IApplicationDbContext' could be found (are you missing a using directive or an assembly reference?)	Application	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Application\Features\Buggers\Commands\Import\ImportBuggersCommand.cs	62	Active	
Error	CS1061	'BuggerDto' does not contain a definition for 'Name' and no accessible extension method 'Name' accepting a first argument of type 'BuggerDto' could be found (are you missing a using directive or an assembly reference?)	Application	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Application\Features\Buggers\Commands\Import\ImportBuggersCommand.cs	62	Active	
Error	CS1061	'IApplicationDbContext' does not contain a definition for 'Buggers' and no accessible extension method 'Buggers' accepting a first argument of type 'IApplicationDbContext' could be found (are you missing a using directive or an assembly reference?)	Application	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Application\Features\Buggers\Commands\Import\ImportBuggersCommand.cs	68	Active	
Error	CS1061	'IApplicationDbContext' does not contain a definition for 'Buggers' and no accessible extension method 'Buggers' accepting a first argument of type 'IApplicationDbContext' could be found (are you missing a using directive or an assembly reference?)	Application	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Application\Features\Buggers\Commands\Update\UpdateBuggerCommand.cs	48	Active	
Error	CS1061	'UpdateBuggerCommand' does not contain a definition for 'Name' and no accessible extension method 'Name' accepting a first argument of type 'UpdateBuggerCommand' could be found (are you missing a using directive or an assembly reference?)	Application	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Application\Features\Buggers\Commands\Update\UpdateBuggerCommandValidator.cs	11	Active	
Error	CS1061	'IApplicationDbContext' does not contain a definition for 'Buggers' and no accessible extension method 'Buggers' accepting a first argument of type 'IApplicationDbContext' could be found (are you missing a using directive or an assembly reference?)	Application	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Application\Features\Buggers\Queries\Export\ExportBuggersQuery.cs	38	Active	
Error	CS1061	'IApplicationDbContext' does not contain a definition for 'Buggers' and no accessible extension method 'Buggers' accepting a first argument of type 'IApplicationDbContext' could be found (are you missing a using directive or an assembly reference?)	Application	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Application\Features\Buggers\Queries\GetAll\GetAllBuggersQuery.cs	35	Active	
Error	CS1061	'IApplicationDbContext' does not contain a definition for 'Buggers' and no accessible extension method 'Buggers' accepting a first argument of type 'IApplicationDbContext' could be found (are you missing a using directive or an assembly reference?)	Application	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Application\Features\Buggers\Queries\GetById\GetBuggerByIdQuery.cs	37	Active	
Error	CS1061	'IApplicationDbContext' does not contain a definition for 'Buggers' and no accessible extension method 'Buggers' accepting a first argument of type 'IApplicationDbContext' could be found (are you missing a using directive or an assembly reference?)	Application	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Application\Features\Buggers\Queries\Pagination\BuggersPaginationQuery.cs	41	Active	
Error	CS1061	'Bugger' does not contain a definition for 'Name' and no accessible extension method 'Name' accepting a first argument of type 'Bugger' could be found (are you missing a using directive or an assembly reference?)	Application	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Application\Features\Buggers\Specifications\BuggerAdvancedSpecification.cs	16	Active	
Error	CS1061	'Bugger' does not contain a definition for 'Name' and no accessible extension method 'Name' accepting a first argument of type 'Bugger' could be found (are you missing a using directive or an assembly reference?)	Infrastructure	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Infrastructure\Persistence\Configurations\BuggerConfiguration.cs	13	Active	
Error (active)	CS0117	'Permissions' does not contain a definition for 'Buggers'	Server.UI	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Server.UI\Pages\Buggers\Buggers.razor	15		
Error (active)	CS0117	'Permissions' does not contain a definition for 'Buggers'	Server.UI	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Server.UI\Pages\Buggers\Buggers.razor	234		
Error (active)	CS0117	'Permissions' does not contain a definition for 'Buggers'	Server.UI	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Server.UI\Pages\Buggers\Buggers.razor	235		
Error (active)	CS0117	'Permissions' does not contain a definition for 'Buggers'	Server.UI	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Server.UI\Pages\Buggers\Buggers.razor	236		
Error (active)	CS0117	'Permissions' does not contain a definition for 'Buggers'	Server.UI	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Server.UI\Pages\Buggers\Buggers.razor	237		
Error (active)	CS0117	'Permissions' does not contain a definition for 'Buggers'	Server.UI	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Server.UI\Pages\Buggers\Buggers.razor	238		
Error (active)	CS0117	'Permissions' does not contain a definition for 'Buggers'	Server.UI	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Server.UI\Pages\Buggers\Buggers.razor	239		
Warning	CS8602	Dereference of a possibly null reference.	Infrastructure	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Infrastructure\Services\ExcelService.cs	129	Active	
Warning	CA1416	This call site is reachable on all platforms. 'Image.FromFile(string)' is only supported on: 'windows'. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)	Infrastructure	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Infrastructure\Services\PaddleOCR\DocumentOcrJob.cs	98	Active	
Warning	CA1416	This call site is reachable on all platforms. 'Image.Save(Stream, ImageFormat)' is only supported on: 'windows'. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)	Infrastructure	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Infrastructure\Services\PaddleOCR\DocumentOcrJob.cs	102	Active	
Warning	CA1416	This call site is reachable on all platforms. 'Image.RawFormat' is only supported on: 'windows'. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)	Infrastructure	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Infrastructure\Services\PaddleOCR\DocumentOcrJob.cs	102	Active	
Warning	CS1998	This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.	Application.IntegrationTests	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\tests\Application.IntegrationTests\Services\PicklistServiceTests.cs	22	Active	
Warning	CS8619	Nullability of reference types in value of type '?' doesn't match target type 'IEnumerable<BuggerDto>'.	Application	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Application\Features\Buggers\Queries\GetAll\GetAllBuggersQuery.cs	39	Active	
Warning	CS8619	Nullability of reference types in value of type '?' doesn't match target type 'BuggerDto'.	Application	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Application\Features\Buggers\Queries\GetById\GetBuggerByIdQuery.cs	40	Active	
Warning	CS8619	Nullability of reference types in value of type '?' doesn't match target type 'PaginatedData<BuggerDto>'.	Application	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Application\Features\Buggers\Queries\Pagination\BuggersPaginationQuery.cs	43	Active	
Warning	SYSLIB0050	'FormatterServices' is obsolete: 'Formatter-based serialization is obsolete and should not be used.' (https://aka.ms/dotnet-warnings/SYSLIB0050)	Application.UnitTests	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\tests\Application.UnitTests\Common\Mappings\MappingTests.cs	51		
Warning	RZ10012	Found markup element with unexpected name 'LandingSection'. If this is intended to be a component, add a @using directive for its namespace.	Server.UI	C:\Users\punko\Downloads\CleanArchitectureWithBlazorServer\src\Server.UI\Pages\Dashboard\Dashboard.razor	210

**Comment by neozhu** [comment]
The error you are getting is because the generated code does not include the Permission class. You need to manually add the permissions for Bugger.
<img width="353" alt="image" src="https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/1549611/13d96c9c-078d-4ad6-9610-56b28d138b9d">

**Comment by punkouter24** [comment]
ok. so its not as simple as add feature. Ill go ahead and manually add the permission piece
