### ISSUE TITLE
[Question] Authentication something keeps looping?

### ISSUE THREAD

**Issue by jochem4207** [neozhu/CleanArchitectureWithBlazorServer#611]
Edit: I pressed enter to quickly, editing now

I've recently got the latest version of the project and sometimes when I open the application (note; debug mode, developing in Rider) the url keeps going to : `https://localhost:44375/pages/authentication/login?ReturnUrl=%2F`

And the error : System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized). comes up in the debug log.

I'm confused as for what I am not authorized as I am trying to log in, did I fu anywhere in setting the repo up, did you have the same issue last weeks/months seen passing by.

[Question, **edited]** Do you have a clue what's going wrong? this happened from very early after copying/cloning the repo. (I am not saying there is a bug, i'm just confused). It does work when I open the private tab window and then I get the log in, so I assume its something cookie related. But in production this is going to be annoying

[Also] Massive thanks this project is helping me a ton! 🚀 

Edit 42:

I also notice after logging in the url doesn't change when I open another page, so when I go the the products page is still /pages/auth instead of /pages/product (or something alike)

**Comment by neozhu** [comment]
<img width="463" alt="image" src="https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/1549611/3f315795-f7a5-49ce-9dc6-4f1c58944e89">
try to clear the token in local storage.

**Comment by neozhu** [comment]
Please note the parameter "UseInMemoryDatabase": false in appsettings.json when debugging. Also, avoid changing the database connection during debugging, as this can also cause the issue. The system stores the user's login TokenString locally. If the database changes after the second login, the stored TokenString will fail verification. That's all, I hope this answer helps!

**Comment by jochem4207** [comment]
Thank you for your explanation if I cannot figure this out later on I will let you know, but I'm very happy that you provided some starting points
