### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by nammadhu** [neozhu/CleanArchitectureWithBlazorServer#635]
<img width="854" alt="image" src="https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/3640748/8cf99b71-5c6b-4718-9c81-6c419d2a27a4">

**Comment by neozhu** [comment]
clear token local storage in browser

**Comment by nammadhu** [comment]
ok sure...
Am closing but is there any permanent solution for this... As this occurring many times and making screen stuck & idle?
