### ISSUE TITLE
Add support for Breadcrumbs

### ISSUE THREAD

**Issue by cptzig** [neozhu/CleanArchitectureWithBlazorServer#636]
Has anyone added support for breadcrumbs? Would it make sense to use fluxor to update them? Or what would be the best strategy to update breadcrumbs in case where we have for instance: 
> /bloggers/:bloggerId/blogs/:blogId

**Comment by neozhu** [comment]
Where do you think would be the most appropriate place to implement the breadcrumb navigation in this scenario?
