### ISSUE TITLE
ConfirmExternal (Login.razor) - security risk

### ISSUE THREAD

**Issue by WimRoegiers** [neozhu/CleanArchitectureWithBlazorServer#641]
If a hacker modifies the javascript and calls the ConfirmExternal directly with a guessed user (for example administrator), I think he will be able to get access. This thanks to the the following lines of code in the beginning of CreateUserWithExternalProvider.

        var user = await UserManager.FindByNameAsync(userName);
        if (user is not null) 
            return user;

***************

Also had in analysed by ChatGTP, he comes to the same conclusion => 

The method ConfirmExternal is designed to be called from JavaScript to finalize the login process after an external authentication provider, like Microsoft, has authenticated a user. However, if a malicious actor can invoke this method directly, bypassing the actual authentication flow, they could potentially log in as any user, assuming they know or can guess the username.

The specific part of the code you highlighted:
var user = await UserManager.FindByNameAsync(userName);
if (user is not null) 
    return user;

This logic finds a user by username and proceeds without verifying that the accessToken corresponds to the user. This approach skips any verification against the external provider to ensure the accessToken is valid and indeed associated with the userName.

**Comment by nammadhu** [comment]
Yes, definitely its an majot loophole here. even am facing the same. Actually using javascript mode you cant verify using secret key thats the major loophole. So shifiting authentication to server side most necessary, especailly in blazor project

**Comment by neozhu** [comment]
@nammadhu @WimRoegiers 
I have already tried, and the login authentication based on cookies is working, but I still fail to log in through Azure AD. I have tried many methods, but in the end, I failed. I don’t know what the problem is. If you are interested, you can fetch the code from the branch named `microsoftauth` and test it by replacing it with your own registered Client Id.
![image](https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/1549611/25142cb2-4a43-4f08-b20b-d43c7067bcd5)

**Comment by neozhu** [comment]
@nammadhu @WimRoegiers 
I did it.
Please check the code from branch 'microsoftauth'.

**Comment by WimRoegiers** [comment]
Hi Neozhu, checking it and until now everything ok, one problem that I have noticed is that the CurrentUserService is not initialized anymore.

**Comment by Bram1903** [comment]
> Can you share a Google auth clientid and client secert with me? My Google developer account cannot be used normally due to regional restrictions. If possible, please help me register an application for the testing of this project.

Hey Neo, do you still need this, and if so, want do you want me to provide to you?

**Comment by neozhu** [comment]
> > Can you share a Google auth clientid and client secert with me? My Google developer account cannot be used normally due to regional restrictions. If possible, please help me register an application for the testing of this project.
> 
> Hey Neo, do you still need this, and if so, want do you want me to provide to you?

thank you for your kind offer! I've resolved. I registered a new Google developer account using a virtual phone number, and now everything is working fine.
