### ISSUE TITLE
application home page unhandled exception

### ISSUE THREAD

**Issue by nammadhu** [neozhu/CleanArchitectureWithBlazorServer#652]
<img width="943" alt="image" src="https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/3640748/794838a5-83d0-43c3-994a-bbe1613cee52">
 
Also more null reference exception. I was on vacation,today only back seeing lot of improvements but sad some these issues.

I tested on main branch only @neozhu  can you help on this ...

Thanks

**Comment by neozhu** [comment]
I tested it on the main branch and didn't see the null reference error. It might be related to your development environment.

**Comment by Alywan** [comment]
I have the same error. Mainly when trying to access the Users page.

**Comment by neozhu** [comment]
> I have the same error. Mainly when trying to access the Users page.

This issue has been fixed.
