### ISSUE TITLE
http error 400. the size of the request headers is too long

### ISSUE THREAD

**Issue by faps25** [neozhu/CleanArchitectureWithBlazorServer#654]
When I deploy it tells me http error 400. the size of the request headers is too long. The only difference is that I have more Claim permissions and apparently it is taking up more space in the HTTP header.

Do they have a way to solve it?

**Comment by neozhu** [comment]
After my tests, this issue doesn't exist. The system automatically splits and stores cookies exceeding 4000, so you don't need to worry about this problem. I don't know why you are getting this error.

![image](https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/1549611/ce0c352f-9322-4b84-96d8-282483e6a415)
