### ISSUE TITLE
QUESTION - How do I run the application locally?

### ISSUE THREAD

**Issue by dirtyblankets** [neozhu/CleanArchitectureWithBlazorServer#663]
Hi there!  How do I run the application locally?  Running 'dotnet run' at Server.UI directory appears to just hang in "Building..." stage but nothing happens.  Any advice would be much appreciated.

**Comment by cptzig** [comment]
Check https://localhost:7256/ and it should be fine, but you have to setup the db first and apply migrations.

**Comment by dirtyblankets** [comment]
@cptzig Ah thank you much!
