### ISSUE TITLE
[Feature] WebAssembly & Auto Render mode

### ISSUE THREAD

**Issue by nammadhu** [neozhu/CleanArchitectureWithBlazorServer#673]
-auto rendermode (.net 8 most promising feature) with webassembly or any other modes 
-Moving razor components to RazorcommonLibrary & invoking in anywhere like Server or WebAssembly or any other mixed mode like Auto... so users will get n number of their dependent ...
-Excluding few server features like Authentication/login or even that also with security

**Comment by nammadhu** [comment]
Hi @neozhu I made PR pls check [https://github.com/neozhu/CleanArchitectureWithBlazorServer/pull/677](PR)

**Comment by Bram1903** [comment]
> Hi @neozhu I made PR pls check [https://github.com/neozhu/CleanArchitectureWithBlazorServer/pull/677](PR)

The moment you create a PR, both Neozhu and I get a notification. Then if you mention him in the PR like you did he gets another notification. The moment you also mention him here he gets three. Perhaps one is enough 😄 

Anyway, thanks for your involvement in this project. It's much appreciated. Neozhu will review your PR once he has time. 

PS. Protip, when you want to mention a PR you can simply tag the PR number. So #677 for example, resolves to that specific PR. 

Kind regards,
Bram

**Comment by nammadhu** [comment]
@neozhu @Bram1903 Is Blazor Wasm AutoRenderMode already enabled, i tried to enable but couldnt be able to cmplete. anychance if you have code with minimal changes (hope program.cs & app.razor),may be other temp branch or PR please share it would be great... For our requirement need to make less server connectivity & use WASM features & Blazore.localstorage so its required... Hope you can understand my request...

**Comment by neozhu** [comment]
This project cannot implement AutoRenderMode.
