### ISSUE TITLE
Public anonymous page logout Antiforgery token issue #NotMajor

### ISSUE THREAD

**Issue by nammadhu** [neozhu/CleanArchitectureWithBlazorServer#676]
<img width="939" alt="image" src="https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/3640748/361a8dae-9709-4805-a391-7666deb4d498">

<img width="828" alt="image" src="https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/3640748/e61ecd82-4d3d-4ba4-a72e-ca64efdbfd3d">

<img width="945" alt="image" src="https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/3640748/213c3934-f41d-4e0a-bced-c71bf64c3d03">

<img width="865" alt="image" src="https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/3640748/caca6392-b7cd-4896-9a07-66a13bdef7b6">

**Comment by neozhu** [comment]
in my tests, everything works fine.
<img width="1031" alt="image" src="https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/1549611/566917b7-8eb0-4ce0-997b-31ea8d4d8bdc">

**Comment by cptzig** [comment]
This is the same problem as I have.

**Comment by neozhu** [comment]
I don't know. Normally, as long as the __RequestVerificationToken has a value, it indicates that everything is working fine. However, I've encountered some issues on mobile during testing, but I'm not sure of the reason yet.
