### ISSUE TITLE
Pull to refresh

### ISSUE THREAD

**Issue by marjanoh2** [neozhu/CleanArchitectureWithBlazorServer#682]
During pull to refresh whole page reloads and shows notifications for user log in/ log out. Is there a better and more smooth way for this situation? 
https://drive.google.com/file/d/1NHvR4KOYynsKsjErPj6aBwBPvVfVAaYR/view?usp=drivesdk

Something similar to this:
https://drive.google.com/file/d/1NHX_-kVFmxM_3kvosCTOa3NDF_j5h399/view?usp=drivesdk

**Comment by neozhu** [comment]
I have refactoring code for this
