### ISSUE TITLE
Is there an easy fix or easy way to remove this functionality ?  (happens after deploying to azure)

### ISSUE THREAD

**Issue by punkouter24** [neozhu/CleanArchitectureWithBlazorServer#684]
An error occurred while starting the application.
DllNotFoundException: Unable to load DLL 'QuestPdfSkia' or one of its dependencies: The specified module could not be found. (0x8007007E)
QuestPDF.Skia.SkNativeDependencyCompatibilityChecker+API.check_compatibility_by_calculating_sum(int a, int b)

InitializationException: The QuestPDF library has encountered an issue while loading one of its dependencies.

Your runtime is currently not supported by QuestPDF. Currently supported runtimes are: win-x64, linux-x64, linux-arm64, linux-musl-x64, osx-x64, osx-arm64.

Please consider setting the 'Platform target' property to 'x64' in your project settings.
QuestPDF.Skia.SkNativeDependencyCompatibilityChecker.Test()

TypeInitializationException: The type initializer for 'QuestPDF.Settings' threw an exception.
QuestPDF.Settings.set_License(Nullable<LicenseType> value)

DllNotFoundException: Unable to load DLL 'QuestPdfSkia' or one of its dependencies: The specified module could not be found. (0x8007007E)
QuestPDF.Skia.SkNativeDependencyCompatibilityChecker+API.check_compatibility_by_calculating_sum(int a, int b)
QuestPDF.Skia.SkNativeDependencyCompatibilityChecker.CheckIfExceptionIsThrownWhenLoadingNativeDependencies()

**Comment by neozhu** [comment]
can you submit a PR for this?

**Comment by punkouter24** [comment]
new to this.. You want me to create a fork and comment out the references to QuestPDF ?

**Comment by neozhu** [comment]
> new to this.. You want me to create a fork and comment out the references to QuestPDF ?

You can create a pull request to fix this issue. I think you just need to change the Dockerfile.

**Comment by punkouter24** [comment]
I don't use the docker file . I deploy as an app service. 

Anyways I just comment out some things related to pdf export and it works

**Comment by neozhu** [comment]
> I don't use the docker file . I deploy as an app service.
> 
> Anyways I just comment out some things related to pdf export and it works

By default, exporting PDF works in English; exporting Chinese characters requires installing a font library.
