### ISSUE TITLE
What is the easiest way to remove the auth/login ? 

### ISSUE THREAD

**Issue by punkouter24** [neozhu/CleanArchitectureWithBlazorServer#686]
So that anon users automatically goto the main page?   Not sure if its a quick setting or I need to make alot of changes?

**Comment by neozhu** [comment]
just change here.
<img width="898" alt="image" src="https://github.com/neozhu/CleanArchitectureWithBlazorServer/assets/1549611/aa1dd51e-873a-444a-8779-5003a85ecde4">

**Comment by punkouter24** [comment]
just comment this out ? still need to log in though


       // services.ConfigureApplicationCookie(options => { options.LoginPath = "/pages/authentication/login"; });

**Comment by neozhu** [comment]
> just comment this out ? still need to log in though
> 
> ```
>    // services.ConfigureApplicationCookie(options => { options.LoginPath = "/pages/authentication/login"; });
> ```
You can access this page without needing to log in.
https://architecture.blazorserver.com/public/index

if you want to disable authentication, you need to remove AddAuthenticationService() function in the infrastructure project
