### ISSUE TITLE
How do I create an migration?

### ISSUE THREAD

**Issue by punkouter24** [neozhu/CleanArchitectureWithBlazorServer#687]
I have been trying different things and nothing works. I added a simple domain object

PS C:\Users\punko\Downloads\PoClean\src\Migrators> cd migrators.sqlite
PS C:\Users\punko\Downloads\PoClean\src\Migrators\migrators.sqlite> dotnet ef migrations add NewMigration --project PoClean.Migrators.MSSQL
MSBUILD : error MSB1009: Project file does not exist.
Switch: C:\Users\punko\Downloads\PoClean\src\Migrators\migrators.sqlite\PoClean.Migrators.MSSQL
Unable to retrieve project metadata. Ensure it's an SDK-style project. If you're using a custom BaseIntermediateOutputPath or MSBuildProjectExtensionsPath values, Use the --msbuildprojectextensionspath option.
PS C:\Users\punko\Downloads\PoClean\src\Migrators\migrators.sqlite>

**Comment by neozhu** [comment]
I suggest you look at the documentation of EF

**Comment by Bram1903** [comment]
Hello @punkouter24, 

Take a look at #433. There I answer the same question with a detailed example.

Kind regards,
Bram

**Comment by punkouter24** [comment]
ok the add-migration works... still can't get the scaffold extension to work though

**Comment by Hoai-Phong** [comment]
I'm trying Migrators.MSSQL but it still doesn't work when creating, can someone describe it to me?
