### ISSUE TITLE
User status and profile update issue

### ISSUE THREAD

**Issue by linkxu1989** [neozhu/CleanArchitectureWithBlazorServer#70]
1. Once switch to login another user and login back to administrator, the previous user will not get offline;
2. If update the user's information from authorization/user page, the profile is not get update Is this get from the different place?

**Comment by neozhu** [comment]
I refactored code about signalrhub.cs

**Comment by linkxu1989** [comment]
Great, how's the status update?
![image](https://user-images.githubusercontent.com/17608441/162738668-14538f56-e08b-4852-ae4d-e5e12aeb5f78.png)

**Comment by linkxu1989** [comment]
![image](https://user-images.githubusercontent.com/17608441/163096478-51e71d7e-a597-4bd5-bb83-54e2b19d4d77.png)

**Comment by neozhu** [comment]
this is a visual sudio.net bug,  it's OK after deployment.

**Comment by linkxu1989** [comment]
Thanks for your update.
