### ISSUE TITLE
[Question] Fetching from remote to local 

### ISSUE THREAD

**Issue by amalsharief** [neozhu/CleanArchitectureWithBlazorServer#714]
Hi, 
Thank you for the brilliant work.
I am new to git. When I create a new project via 

dotnet new ca-blazorserver-sln -n CleanGit

Is it possible to connect my local repository to the remote 
https://github.com/neozhu/CleanArchitectureWithBlazorServer
to get all changes pull requests to the local repo?
If yes, how can I do that?

Thank you 

amalsharief

**Comment by neozhu** [comment]
I don't think so. You can only merge the code manually. I think it will take some effort to do so.

**Comment by rwxzig** [comment]
You can use this command to add a new remote: 
`git remote add cleanarch https://github.com/neozhu/CleanArchitectureWithBlazorServer.git`
Note that `cleanarch` is the name of the remote and you can call that whatever you want. 

And then you can use `git fetch/pull remote cleanarch` to pull from it.
But then, as @neozhu mentioned, you need to fix the merge conflicts manually, unless you want to have the code exactly as the original.

**Comment by Bram1903** [comment]
@amalsharief, did this answer your question?
