### ISSUE TITLE
Reading value from user preferences on dashboard page, always returns the default value on the first render.

### ISSUE THREAD

**Issue by rwxzig** [neozhu/CleanArchitectureWithBlazorServer#717]
I am trying to add another value at user preferences so that I can save on local storage and use this value in Layout and dashboard page.

I began by adding the field on `UserPreferences.cs`
```cs
public bool Auction { get; set; }
```
And then on my `LayoutService.cs`
```cs
public bool Auction { get; set; } = true;
```

I update it by invoking this method on `LayoutService.cs`
```cs
public async Task SetIsAuction(bool value)
{
    Auction = value;
    UserPreferences.Auction = Auction;
    await UserPreferencesService.SaveUserPreferences(UserPreferences);
    OnMajorUpdateOccured();
}
   ```
On the dashboard page I have a switch button which is being used to switch the Auction on and off like this:
```cs
<MudSwitch T="bool" Value="@LayoutService.Auction" Label="@(LayoutService.Auction? "Auction" : "N/A")" ValueChanged="@(e => OnAuctionUpdate(e))" />
```

And this is the `OnAuctionUpdate` method from the dashboard page:
```cs
private async Task OnAuctionUpdate(bool value)
{
    LayoutService.Auction = value;
    await LayoutService.SetIsAuction(value);
    StateHasChanged();
}
```

Although the value on the local storage is being updated when I switch, the problem is that when I reload, it always gets the default value which is defined on the `LayoutService.cs`

Do you have any idea on how to fix this issue?
Best regards and thanks in advance.

Cheers.

**Comment by neozhu** [comment]
```c#
 public async Task ApplyUserPreferences(bool isDarkModeDefaultTheme){
...
}
```
The `ApplyUserPreferences` method will load the saved configuration each time; your code needs to assign values to your parameters here.

**Comment by rwxzig** [comment]
I am already applying, and the parameters are assigned correctly, but on the first load, it shows the default values and not the values that are stored on local storage.
