### ISSUE TITLE
Demo Site - Microsoft OAuth token endpoint failure - expired

### ISSUE THREAD

**Issue by ghhv** [neozhu/CleanArchitectureWithBlazorServer#727]
https://architecture.blazors.app/

AuthenticationFailureException: OAuth token endpoint failure: invalid_client;Description=AADSTS7000222: The provided client secret keys for app '1485d804-9411-4701-964f-b1ad7a0d9ee3' are expired.

**Comment by neozhu** [comment]
fixed, Please try it again

**Comment by ghhv** [comment]
Using Microsoft got this error:
`We're unable to complete your request
invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application.`

**Comment by ghhv** [comment]
Google:
`Username '<name>@gmail.com' is already taken. Email '<name>@gmail.com' is already taken.`
Can't seem to login - trying to re-register me??

**Comment by ghhv** [comment]
The Admin test login also says
`Error: Your account is inactive. Please contact support.`

**Comment by neozhu** [comment]
first delete your account
