### ISSUE TITLE
Create Multiselect components

### ISSUE THREAD

**Issue by Hkarimi1364** [neozhu/CleanArchitectureWithBlazorServer#734]
Please Create Multiselect Components

**Comment by neozhu** [comment]
What's the use?

**Comment by Hkarimi1364** [comment]
It is usually used for data storage
For example, registering tags

**Comment by xenOIvan** [comment]
if you mean somthing like this it would be totaly usefull 🙏

![image](https://github.com/user-attachments/assets/e85c3a6f-bf3d-4766-b1c8-f3fb9e4337a5)

**Comment by neozhu** [comment]
This does not require additional development. mudblazor mudselect can already support multiple selection.

**Comment by Hkarimi1364** [comment]
Can you give an example for inserting, filtering and editing?
