### ISSUE TITLE
Converting the template to Auto or WebAssembly render mode

### ISSUE THREAD

**Issue by rwxzig** [neozhu/CleanArchitectureWithBlazorServer#736]
What are limitations of this architecture regarding converting this template to WebAssembly or Auto render mode?

**Comment by neozhu** [comment]
impossible! only WebAssembly project can be switched to auto render mode or server render mode.

**Comment by rwxzig** [comment]
Theoretically what would it take? The current architecture does not allow it, but what would it take to convert it to a WebAssembly project that can switch between render modes?
