### ISSUE TITLE
ShowEditFormDialogWithGeneric ( Suggestion )

### ISSUE THREAD

**Issue by stevsharp** [neozhu/CleanArchitectureWithBlazorServer#740]
Hey there! I recently downloaded this great project and started creating a simple application to learn the platform. I made a small fix that allows the dialog to open in a generic way. It's not a big change, but I wanted to contribute a little.

Here is the code

public interface IFormDialog<TCommand> where  TCommand : ICacheInvalidatorRequest<Result<int>>
{
    Action? Refresh { get; }
    TCommand model { get; set; }
}

public partial class SurgeryFormDialog : ComponentBase, IFormDialog<AddEditSurgeryCommand>
{
    MudForm? _form;
    private bool _saving = false;
    private bool _savingnew = false;
    [CascadingParameter]
    MudDialogInstance MudDialog { get; set; } = default!;
    AddEditSurgeryCommandValidator _modelValidator = new();
    [EditorRequired][Parameter] 
    public AddEditSurgeryCommand model { get; set; } = null!;
    public Action? Refresh { get; }
}

    private async Task ShowEditFormDialogWithGeneric<TDialog, TCommand>(string title, TCommand command)
    where TDialog : ComponentBase, IFormDialog<TCommand>
    where TCommand : ICacheInvalidatorRequest<Result<int>>
    {
        var parameters = new DialogParameters
    {
        { nameof(IFormDialog<TCommand>.Refresh), (Func<Task>)(() => _table.ReloadServerData()) },
        { nameof(IFormDialog<TCommand>.model), command }
    };

        var options = new DialogOptions { CloseButton = true, MaxWidth = MaxWidth.Medium, FullWidth = true };
        var dialog = DialogService.Show<TDialog>(title, parameters, options);
        var state = await dialog.Result;

        if (!state.Canceled)
        {
            //await _table.ReloadServerData();
            //_selectedItems.Clear();
        }
    }

**Comment by neozhu** [comment]
Could you create a PR# for this change
