### ISSUE TITLE
CleanArchitectureCodeGenerator a .NET 8 console application

### ISSUE THREAD

**Issue by veerendra-shakya** [neozhu/CleanArchitectureWithBlazorServer#746]
hi neozhu,

https://github.com/veerendra-shakya/CleanArchitectureCodeGenerator.git  

I wanted to share a project I’ve been working on: CleanArchitectureCodeGenerator. This is an informative code generator tailored specifically for your CleanArchitectureWithBlazorServer project.

Based on your original scaffolder, I’ve addressed several issues, such as requiring the Name and Description fields, removing Entities/features, and improving the overall scaffolding process. I believe these updates make the tool more user-friendly and aligned with clean architecture principles.

I’d love it if you could review it and provide your remarks or suggestions.

Thanks in advance!

Best regards,
Veerendra Kumar Shakya

**Comment by neozhu** [comment]
super!

**Comment by neozhu** [comment]
Hi Veerendra,

Thank you for sharing your project! It looks great, and I appreciate the improvements you’ve made.

Could you please submit a PR to merge your updates into my project, especially the changes related to the DB Context Modifier Added and the EF Configuration Generator? I believe these additions would be a valuable enhancement to the project.

Looking forward to your contribution!

Best regards,  
neozhu

**Comment by veerendra-shakya** [comment]
[PropertyCategoryAttribute.zip](https://github.com/user-attachments/files/16941433/PropertyCategoryAttribute.zip)

only one attribute class added by me in CleanArchitectureWithBlazorServer project. in folder  CleanArchitectureWithBlazorServer-main\src\Domain\Common\Attributes\PropertyCategoryAttribute.cs   to support CleanArchitectureCodeGenerator a .NET 8 console application
