### ISSUE TITLE
Request to Add API Project for Mobile Application Support with JWT Authentication

### ISSUE THREAD

**Issue by veerendra-shakya** [neozhu/CleanArchitectureWithBlazorServer#752]
Hello neozhu,

First, I want to commend you on the excellent work with the Blazor Server project. The current solution is an excellent fit for developing administrative and data management portals. Blazor Server provides a rich, interactive experience, making it a great choice for internal tools or administration dashboards.

However, for public-facing applications, especially in scenarios where a majority of users are mobile-based, it's important to consider a more mobile-optimized approach. 

Request:
Could you please consider adding a separate API project to the solution? This API would serve as a backend for mobile applications, allowing more flexibility in terms of front-end technology.

Specifically, I suggest:

Adding a new API project based on .NET 8 to the solution.
Implementing JWT token-based authentication for secure access to the API endpoints, ensuring mobile clients can authenticate and manage their sessions efficiently.

Benefits:
This would allow the Blazor Server project to remain focused on internal tools and administrative use cases.
It will provide a robust, scalable API backend for public-facing mobile applications.
By utilizing JWT tokens, we can ensure that mobile clients can authenticate securely and interact with the system without requiring persistent connections.

Thank you for considering this feature. I believe it would be a valuable addition to this project and help align it with the needs of modern web and mobile application development.

further i will integrate it with my console based scaffolding tool to automatically generate controllers in API project, but i need your support to provide me sample API project implementation.

Best regards,
Veerendra Kumar Shakya

**Comment by neozhu** [comment]
I’ve implemented it before, but I gave up on it, so I’m not planning to implement JWT authentication in this version. Thank you for your suggestion.
