### ISSUE TITLE
New Feature: Login with Phone OTP Now Available!

### ISSUE THREAD

**Issue by sunilsoni761** [neozhu/CleanArchitectureWithBlazorServer#789]
Dear  Neozhu,
We’re excited to introduce a new, easier way to log in to your account—Phone OTP Login!

Now, you can log in by simply entering your phone number, and we’ll send you a One-Time Password (OTP) via SMS. No need to remember your password, just use the OTP to access your account securely.

Here’s how it works:

1. Enter your registered phone number.
2. Receive the OTP via SMS.
3. Enter the OTP and access your account!

This feature is designed to make your login experience faster, simpler, and more secure.

If you have any questions or need assistance, feel free to reach out to our support team at [Support Email/Phone].

Thank you for being a valued user!

**Comment by sunilsoni761** [comment]
In page identify authentication can't see login from phone and validate OTP without password

**Comment by neozhu** [comment]
I don't know how to implement the Phone OTP. Also, collecting users' phone numbers on a demo website may not be a good practice.

**Comment by sunilsoni761** [comment]
I need want to login user with phone and otp send to mail and opt authentication after login can you share code I will implement

**Comment by neozhu** [comment]
this is a public repository. You can pull and make changes as you wish.

**Comment by Bram1903** [comment]
Using SMS for multi-factor authentication is considered a weak practice due to several significant vulnerabilities. Instead, users should opt for authentication apps or security keys as more secure alternatives for two-factor authentication. Learn more: https://sec.okta.com/articles/2020/05/sms-two-factor-authentication-worse-just-good-password

**Comment by rwxzig** [comment]
Talking about this, is there any plan for implementing passkeys in this template?
