### ISSUE TITLE
Issue with Riok.Mapperly Crashing on Simple Object Mappings

### ISSUE THREAD

**Issue by stevsharp** [neozhu/CleanArchitectureWithBlazorServer#804]
Good morning,

I am experiencing an issue with Riok.Mapperly when mapping two simple objects in my solution. After generating the mapping for commands and UI, the solution crashes during the build process. The error points to Mapperly, even though the objects being mapped are straightforward.

Here are the classes I'm mapping:

public class OfferLine : BaseAuditableEntity
{
    public int OfferId { get; set; }
    public int ItemId { get; set; }
    public int Quantity { get; set; }
    public decimal Discount { get; set; }
    public decimal LineTotal { get; set; }

    public Offer Offer { get; set; } = null!;
}

public class Offer : BaseAuditableEntity
{
    public int CustomerId { get; set; }
    public DateTime OfferDate { get; set; } = DateTime.UtcNow;
    public decimal TotalAmount { get; set; }
    public string Status { get; set; } = "Pending";

    public Contact? Customer { get; set; }
    public List<OfferLine> OfferLines { get; set; } = new();
}
Despite the simplicity of these classes, the solution crashes, and the error log points to a Mapperly-related issue. The error occurs during the mapping generation step and looks like this:
Here’s what I’ve tried so far:

Verified that all properties are properly initialized and used nullability annotations where necessary.
Cleaned the solution and rebuilt it multiple times.
Added debug logging for Mapperly to investigate the issue.
Does anyone have suggestions on how to resolve this issue? Could it be related to circular references or unsupported scenarios in Mapperly? Any advice or best practices for debugging Mapperly would be appreciated.

Thank you in advance for your help!

7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Nullable1[[Riok.Mapperly.Output.MapperAndDiagnostics, Riok.Mapperly, Version=4.1.1.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].UpdateStateTable(Builder, Microsoft.CodeAnalysis.NodeStateTable1<System.Nullable1<Riok.Mapperly.Output.MapperAndDiagnostics>>, System.Threading.CancellationToken)
    C:\Program Files\dotnet\sdk\9.0.101\Roslyn\Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.DriverStateTable+Builder.GetLatestStateTableForNode[[System.Nullable1[[Riok.Mapperly.Output.MapperAndDiagnostics, Riok.Mapperly, Version=4.1.1.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](Microsoft.CodeAnalysis.IIncrementalGeneratorNode1<System.Nullable1<Riok.Mapperly.Output.MapperAndDiagnostics>>)
    C:\Program Files\dotnet\sdk\9.0.101\Roslyn\Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.TransformNode2[[System.Nullable1[[Riok.Mapperly.Output.MapperAndDiagnostics, Riok.Mapperly, Version=4.1.1.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Nullable1[[Riok.Mapperly.Output.MapperAndDiagnostics, Riok.Mapperly, Version=4.1.1.0, Culture=neutral, PublicKeyToken=null]], System.Privat

**Comment by neozhu** [comment]
The issue is caused by circular references between your Offer and OfferLine classes. To resolve this, you need to break the circular reference by ignoring one of the properties during mapping. You can use the MapperIgnore attribute provided by Mapperly.

**Comment by stevsharp** [comment]
I decided to step back for now... The application keeps crashing, and the issue is truly puzzling.

**Comment by neozhu** [comment]
You should not include it when querying from the source linq.

**Comment by stevsharp** [comment]
The process was terminated due to a StackOverflowException. The mapping is straightforward and follows EF Core's recommended patterns. I really do not undestand the reason why this message is displayed .

public class Offer : BaseAuditableEntity
{
    public int CustomerId { get; set; }
    public DateTime OfferDate { get; set; } = DateTime.UtcNow;
    public decimal TotalAmount { get; set; }
    public string Status { get; set; } = "Pending";

    public List<OfferLine> OfferLines { get;set; } = new List<OfferLine>();
}

public class OfferLine : BaseAuditableEntity
{
    public int OfferId { get; set; }
    public int ItemId { get; set; }
    public int Quantity { get; set; }
    public decimal Discount { get; set; }
    public decimal LineTotal { get; set; }

    [MapperIgnore()]
    public Offer Offer { get; set; }   = new Offer();
}

public class OfferLineConfiguration : IEntityTypeConfiguration<OfferLine>
{
    public void Configure(EntityTypeBuilder<OfferLine> builder)
    {
        builder.HasOne(x => x.Offer).WithMany(x=>x.OfferLines).HasForeignKey(x => x.OfferId); 

        builder.Ignore(e => e.DomainEvents);
    }
}

**Comment by stevsharp** [comment]
I managed to work in this way 

public class OfferConfiguration : IEntityTypeConfiguration<Offer>
{
    public void Configure(EntityTypeBuilder<Offer> builder)
    {
        builder.ToTable("Offer");

       builder.Property(x => x.Status).HasMaxLength(255);

        builder.OwnsMany(o => o.OfferLines, x =>
        {

        });

        builder.Ignore(e => e.DomainEvents);
    }
}

The OfferLines are no longer set as DbSet in DbContext and the query works 


public async Task<IEnumerable<OfferDto>> Handle(GetAllOffersQuery request, CancellationToken cancellationToken)
{
    var data = await _context.Offers
                                    .Include(x=>x.OfferLines)
                                    .ProjectTo()
                                    .AsNoTracking()
                                    .ToListAsync(cancellationToken);
    return data;
}
