### ISSUE TITLE
Feature Request: API

### ISSUE THREAD

**Issue by RoLYroLLs** [neozhu/CleanArchitectureWithBlazorServer#807]
Great project and thanks for keeping it updated.

I think it would be great if this project can abstract it's data calls via an API.

For me own project, I'm going to start working on adding a separate project to host the API as a separate client, however, I've seen other Clean Architectures, like the one I came from [Blazor Starter Kit](https://github.com/fullstackhero/blazor-starter-kit), layer out the data calls.

I'll try my best to adda PR for this, but I'm not confident in my skills just yet for a project like this.

**Comment by neozhu** [comment]
I believe adding an extra API layer in a Blazor Server project may add unnecessary complexity.
