### ISSUE TITLE
Concurrent Issue on DbContext

### ISSUE THREAD

**Issue by khaledtaleblari** [neozhu/CleanArchitectureWithBlazorServer#810]
This is usually caused by different threads concurrently using the same instance of DbContext.

**Comment by neozhu** [comment]
which page? can you share more detail error message?

**Comment by khaledtaleblari** [comment]
System.InvalidOperationException: 'A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext
![error](https://github.com/user-attachments/assets/2fc2d95f-d8fe-432f-bc67-4d823d895d41)

**Comment by khaledtaleblari** [comment]
I tried to add Semaphore to bypass the error still the same.
I have created a full project customizing your awesome architecture and desgin.
Thanks alot

**Comment by neozhu** [comment]
Does the query of the template have this problem? There is no such error in my deployment environment.

**Comment by khaledtaleblari** [comment]
No there isnt
i have created another page using the DbContext as the same pattern you are following.Then it raising error

**Comment by neozhu** [comment]
I might have guessed the cause of this issue. Are you performing the query in the `OnInitializedAsync` method? If so, this might lead to the problem. Please try moving the query to the `OnAfterRenderAsync` method, or disable prerendering by using `InteractiveServerRenderMode(false)`.

**Comment by khaledtaleblari** [comment]
**i have tried to get the IApplicationDbContext from the IServiceProvider and injected in the Handler so it worked perfectly.**
public class GetQuestionsByQuizIdQueryHandler :
 IRequestHandler<GetQuestionsByQuizIdQuery, List<QuestionDto>>
{
    private readonly IServiceProvider _serviceProvider;
    public GetQuestionsByQuizIdQueryHandler(IServiceProvider serviceProvider)
    {
        this._serviceProvider = serviceProvider;
    }

    public async Task<List<QuestionDto>> Handle(GetQuestionsByQuizIdQuery request, CancellationToken cancellationToken)
    {
        await using (var scope = _serviceProvider.CreateAsyncScope())
        {
            var _context = scope.ServiceProvider.GetRequiredService<IApplicationDbContext>();

            var data = await _context.Questions
         .AsNoTracking()
         .ApplySpecification(new QuestionByQuizIdSpec(request.QuizId))
                  .ProjectTo()
                  .AsNoTracking()
                  .ToListAsync(cancellationToken);
            if (data is null || data.Count == 0)
                return default!;

            return data;
        }
    }
