### ISSUE TITLE
Log could not be seen after published.

### ISSUE THREAD

**Issue by linkxu1989** [neozhu/CleanArchitectureWithBlazorServer#91]
![image](https://user-images.githubusercontent.com/17608441/165253558-8ad1e6cb-94e8-4bcc-868a-9ea95abc8a7c.png)
Why the logs is not present after published to IIS server?

**Comment by neozhu** [comment]
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/1549611/165273042-485625e0-3f3a-4a41-8f64-e7c6d168488e.png">
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/1549611/165273088-19f912f9-ac27-4b81-ae3a-fc31c7ad424c.png">
The above two configurations are the same

**Comment by linkxu1989** [comment]
Awesome, thanks.
